### ISSUE TITLE
Multichart only displays hover dots and no actual information

### ISSUE THREAD

**Issue by marcopiani** [owid/owid-grapher#1046]
Hi,

many thanks for constantly improving the the tools OWID provides for data exploration.

I think that the introduction of subplots to display multiple metrics at once is incredibly useful.

One issue is that there is no information-rich tooltip like instead one has in single charts, rather just hovering dots. See attached images.

One additional reason why this is an issue is that it might be difficult to tell apart the series in each plot, given that the color palette makes it difficult to begin with, and it is even more difficult now that the subplot are necessarily smaller.

It would also be good to have the latest values displayed, as it is done in the standard single-chart plots.

Thank you again, also for potentially addressing this issue.

Marco

![t1zf8wd9](https://user-images.githubusercontent.com/18381804/143289780-9f7742cc-025a-4af0-a0a7-06a71a505fa9.png)

![jZZ9NJhg](https://user-images.githubusercontent.com/18381804/143289724-2f50829a-d8f3-4fdf-884b-d222089232f3.jpg)

**Comment by danielgavrilov** [comment]
Thanks for reporting this Marco! And for all the great charts you’ve made during this pandemic.

This is an issue that annoys me every time I look at one of these charts! 

But it’s also unfortunately an issue that will take some time because it requires rearchitecting how tooltips are implemented in our graphing tool. Because of that, it has slipped down our priorities list, and unlikely to be fixed before Christmas time 🎄 🙁 (...unless we come up with some quick & clever intermediate patch, which sometimes someone manages to pull off)

**Comment by marcopiani** [comment]
Many thanks for the reply, and for the kind words.

I appreciate that it may not be an easy fix. Thanks again for all the work you are doing!

**Comment by larsyencken** [comment]
Thanks Marco, collecting it into another issue for us to fix in the future: https://github.com/owid/owid-grapher/issues/1084

**Comment by marcopiani** [comment]
Thanks!

I see you implemented it. Many thanks!

I do not know how easy this is now, but here is the suggestion of a possily easy to implement additional feature https://github.com/owid/owid-grapher/issues/1084#issuecomment-1130196917
