### ISSUE TITLE
Scatterplots: some points not sized by population

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1088]
Notion parent issue: https://www.notion.so/owid/ScatterPlot-Some-points-not-sized-by-population-8587e771048040509486ce3f848aa4fa

## Problem

One at least one occasion a scatterplot was reliably not sizing China by its population.

## Expected behaviour

Each item should be correctly sized.

**Comment by larsyencken** [comment]
@danielgavrilov mentioned that it's probably better tackled in https://github.com/owid/owid-grapher/issues/1091

I wasn't sure how to reproduce this, tempted to mark as won't fix and close it.

**Comment by danielgavrilov** [comment]
There used to be various bugs with joining tables and tolerance, causing missing or incorrect data. They've been getting fixed over time ([most recently this](https://github.com/owid/owid-grapher/commit/dd8fb85fa7bfff31e7eea0cb3b0d127d97b3778a)), with only the bigger ones remaining that require some restructuring in how tolerance is specified and handled, e.g. https://github.com/owid/owid-grapher/issues/1091.

So, I'm guessing one of those fixes also fixed this issue, because I can't reproduce it either.
