### ISSUE TITLE
Map brackets should always be equal bin by default

### ISSUE THREAD

**Issue by HannahRitchie** [owid/owid-grapher#1113]
## Core problem

Map brackets can either be equally-spaced or not – the author currently sets this option. But, especially for some charts with large ranges, this makes some of the brackets unusable.

Example of [not equally spaced](https://ourworldindata.org/grapher/gdp-per-capita-worldbank) (there are worse examples where the bottom brackets are not hoverable) vs. [equally spaced](https://ourworldindata.org/grapher/gross-domestic-product).

## Proposed solution

We would like map bracket bins to be equally-spaced by default, and for all previous charts to adopt this behaviour. i.e. all maps on OWID should have equal bin spacing.

**Comment by larsyencken** [comment]
## Proposed change

Just been looking at this now. So, there is _visual bin spacing_ and _numeric bin spacing_. Heaps of maps lose detail unless you use numeric bins that are nearly logarithmically spaced (e.g. 1, 2, 5, 10, 100, 500, 1000). When the visual spacing matches this logarithmic spacing, then some of the bins are too small to hover on.

The proposed solution is to always visually space bins evenly, without changing the often logarithmic numeric spacing. Have I understood right Hannah?

## Technical approach

- Ignore the `equalSizeBins` config key and simply force it to `true`
- Update the schema to remove this config key
- Do a migration or otherwise bulk prune the key from existing configs

**Comment by HannahRitchie** [comment]
Yes, that's correct @larsyencken. 

We **do not** want to force equal numeric spacing. But we **do** want to force equal visual spacing.

**Comment by danielgavrilov** [comment]
I will go through some old charts and see if there are any potential issues, and bring them up for discussion.

**Comment by danielgavrilov** [comment]
Are we sure we want to remove this feature completely? Some charts, like the Food Explorer, I think work better when sized linearly: 

<a href="https://ourworldindata.org/explorers/global-food?facet=none&Food=Wheat&Metric=Production&Per+Capita=false&country=USA~DEU~FRA~GBR~BRA~ZAF"><img src="https://user-images.githubusercontent.com/1308115/159256646-4faeca81-1258-48b4-9fdc-88f7bd2448f7.png" width=650 /></a>

Compared to equal size:

<a href="https://ourworldindata.org/explorers/global-food?facet=none&Food=Wheat&Metric=Production&Per+Capita=false&country=USA~DEU~FRA~GBR~BRA~ZAF"><img src="https://user-images.githubusercontent.com/1308115/159256840-b734c441-541a-44a9-a254-975208442a16.png" width=650 /></a>

Also in this case I prefer the linearly scaled version:

<a href="https://playfair-owid.netlify.app/grapher/share-of-children-vaccinated-against-measles?country=~OWID_WRL"><img src="https://user-images.githubusercontent.com/1308115/159257370-c5062572-6fa2-4a61-aae2-24f0d59cfb51.png" width=650 /></a>

@HannahRitchie @maxroser Can you confirm we definitely want to get rid of the feature, including for the charts above? Or would you prefer to keep it for some charts?

**Comment by danyx23** [comment]
For what it's worth I would definitely keep it as an option
