### ISSUE TITLE
Stacked bar charts drop the entity title when multiple entities are forced

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1124]
## Description

Stacked bar charts (over time) normally only allow one entity to be selected per chart. But it is possible to force them into multi-entity mode, by selecting too many in the admin, or by adding GET parameters for multiple entities.

When you do this, only the last entity gets plotted, but its title is missing so that the behaviour appears undefined.

## Expected behaviour

Ideally, we would plot the title of the selected entity, so that it's clear that only one got selected in the end. Faceting the result would also be a valid outcome.

## Examples

https://ourworldindata.org/grapher/deaths-by-age-group-stacked?country=CHL~SAU~ARE

## Screenshots

<img width="1092" alt="Screenshot 2022-02-01 at 14 20 32" src="https://user-images.githubusercontent.com/36012/151974783-2dae9e52-689a-4408-b7ac-efd0af64be27.png">

## Reported by

@maxroser

**Comment by larsyencken** [comment]
This happens via search because search auto-added a multi-country selection for something that was only single-country.

**Comment by larsyencken** [comment]
Technical note: might need to add a layer between the selection object and anything that accesses it, which is where this fix could go.

**Comment by maxroser** [comment]
The same problem is much more salient in the Explorer (because the country selector is available to the user) — reported it here: https://owid.slack.com/archives/C46U9LXRR/p1656511094349459

**Comment by larsyencken** [comment]
Reviewed again with @danyx23, we still think this is important to fix

**Comment by marcelgerber** [comment]
The country profile working group got very confused by this issue today, we also think this is important to fix.

**Comment by larsyencken** [comment]
I tagged this one for next cycle.

**Comment by marcelgerber** [comment]
Currently, the thinking here is to enable faceting by entity by default for these stacked charts where there's multiple entities selected. I and Daniel cannot think of a case where this could go wrong.

We can also think about offering the "Facet by" dropdown in this case by default, because faceting by metric is also an useful option in many of these cases. Guess we'll try it out and see if there are any cases where this doesn't work out well.

One other thing to work out is how this all should behave when the timeline is collapsed to a single year. Currently, this ends faceting in most cases, but we'll have to rework that. Potentially, that's part of #1695.

The above chart would look like this when faceted:
![image](https://user-images.githubusercontent.com/2641501/202855694-bc66bebb-bb3d-42d1-ba9f-94fd53eca2ed.png)
