### ISSUE TITLE
Context sensitive FASTT (change depending on "dimension" or chart type or variable)

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1176]
## Core problem

The more our charts can change what they show the more the need comes up to change the title and subtitle for them (e.g. a map chart that shows the median estimate and a facetted line chart that can show confidence intervals + median estimate). 

Once we make it easier to see per capita metrics in the grapher this will become more urgent. Also once we are able to switch between all/most chart types for every chart this will become much more important - #1162 

## Proposed solution

This is still to be figured out. The tricky part is that we will probably want to have a strong fallback mechanism so that you describe this once and then different "views" can be set to override this. But how to store this in the grapher config in a way that is nice to migrate forward and that works well with the grid editing view that we are now building for the #1052 is a tricky question.

## Alternatives

Create new charts for cases where the FASTT should differ and use small explorers to group them together.

## Context

One way this manifests today is with the map and line chart views of [excess mortality due to Covid](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&uniformYAxis=0&pickerSort=asc&pickerMetric=location&Metric=Excess+mortality+%28estimates%29&Interval=7-day+rolling+average&Relative+to+Population=true&Color+by+test+positivity=false&country=USA~GBR~CAN~DEU~ITA~IND). Here the map subtitle should caution that only the median estimate is shown on the map, whereas on the line chart such a disclaimer is not needed and may be confusing.

Another place where this comes up is this [vaccination chart](https://ourworldindata.org/covid-deaths-by-vaccination#switzerland). Here if all age groups are shown then the variable you see is age standardised. But if you switch the variable and look at one age group only then this is no longer age standardizes.

**Comment by danyx23** [comment]
This is not urgent now but will probably become so once #1162 is rolled out.

**Comment by danyx23** [comment]
The original notion card where Max reported the issues is here: https://www.notion.so/owid/The-FASTT-needs-to-be-different-dependent-on-which-dimension-is-displayed-in-a-chart-6aee82c85aba42a28deb453da04b2baf

**Comment by larsyencken** [comment]
It sounds like we're discussing the ability to write custom FASTT per entity that we're viewing, which sounds like a deep spiral of pain, although if we moved this to an explorer and change how the data is modelled we can already do this.

I'm not convinced this has a good technical solution, it's more about how we use our tools and the constraints that we live with within them.

**Comment by danyx23** [comment]
Not really per entity but per chart type or configuration probably. We already have a few changes to the title that we automate (e.g. if you turn on relative) and I think this can be thought of as a generalization of this problem. Once every chart is more or less able to show every type of chart this will become more urgent.

**Comment by bastianherre** [comment]
Hey! Daniel asked me to share two more examples of this issue here: 

1) Sometimes we have charts where the user can display either absolute or relative numbers by marking the Relative toggle, such as this chart on the [people living in democracies](https://ourworldindata.org/grapher/people-living-in-democracies?country=~OWID_WRL). The issue is that for some charts it is difficult to find a title that works well for both the absolute and relative views; we then have to create separate charts, such as for these charts on the [number](https://ourworldindata.org/grapher/number-democracies?country=~OWID_WRL) and [share](https://ourworldindata.org/grapher/share-democracies?country=~OWID_WRL) of democracies.

2.) Sometimes we have notes that are only relevant to the chart view and not the map, such as in [this chart](https://ourworldindata.org/grapher/political-regime).

I hope this is helpful!
