### ISSUE TITLE
Easier to set color scale on maps

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1185]
Author: @CGiattino 
Author-rated priority: Low
Completed?: No
Created on: December 13, 2021 9:13 PM
Description: It's hard to set the color scale when it's asymmetric, e.g. here: https://owid.cloud/admin/charts/5458/edit. DanielG had an idea here: https://owid.slack.com/archives/C0149NKLZAM/p1637171715003600?thread_ts=1637171361.003100&cid=C0149NKLZAM
Last modified: December 14, 2021 4:22 PM
tags: Author request

Max has mad hacks to work around this, it could definitely be easier.

**Comment by larsyencken** [comment]
It turns out it's hard to add custom colours to modify a colour scale, because a scale helpfully rebalances with each step you add. For example, making the very first blue bin was hard for this chart:

<img width="774" alt="Screen Shot 2022-03-01 at 12 44 16" src="https://user-images.githubusercontent.com/36012/156163342-c237a7f3-c00f-4c61-a3d7-0b81de8bbde0.png">

It seems like the underlying issue is not being able to set the midpoint (for diverging palettes) or the start point (for sequential palettes). So the proposed solution would be to add a new admin field and corresponding config options to make this work.

**Comment by larsyencken** [comment]
Marking it as won't fix right now, since there's a workaround. We can revisit if we are otherwise changing colour scales. We can pick it up again if authors tell us it's become more painful.
