### ISSUE TITLE
Make stacked area = stacked bar where only one year is selected

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1191]
Author: @JoeHasell 
Completed?: No
Created on: January 10, 2022 4:11 PM
Last modified: January 10, 2022 4:15 PM
priority: Low
tags: Author request

Currently, when the timespan selected is only one year (e.g. 2017-2017), then no data gets shown in the chart (although data is given in the table tab). I think it would be better for it to turn into a stacked bar chart for this one year. 

E.g. [https://ourworldindata.org/grapher/distribution-of-population-between-different-poverty-thresholds-up-to-30-dollars?stackMode=relative&time=2017&country=~CHN](https://ourworldindata.org/grapher/distribution-of-population-between-different-poverty-thresholds-up-to-30-dollars?stackMode=relative&time=2017&country=~CHN)

This can be helpful for saying 1) ‘Here is how things stand today’; 2) ‘Here is how they’ve changed’.

**Comment by larsyencken** [comment]
This relates to behaviour we have on the line chart, where it collapses to a bar chart if only a single year is selected. We want to do the same thing for stacked area.

This is in our "reduce the scatteredness of OWID" theme, since it lets you make less charts and have them instead collapse to one-another based on settings.

**Comment by marcelgerber** [comment]
Fixing the underlying StackedArea issue should also work, right?
Basically making it so that a single-year StackedArea is just a very wide StackedBar chart, and not broken as it currently is on live (left).
![image](https://user-images.githubusercontent.com/2641501/161378882-c88d69d0-0506-4d9e-aefc-35a759b6799f.png)
