### ISSUE TITLE
Chart should be aware of references coming from sdg-tracker.org or explorers

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1194]
## Core problem

We're currently trying to get rid of some dusty charts, but [in the process it's very easy to delete charts](https://owid.slack.com/archives/C01GAN73R5W/p1645106828735349) that are still referenced somewhere.

## Proposed solution

The existing "References" tabs in the Grapher admin should be aware of references coming from sdg-tracker.org.
It should also be aware of `grapherId`s referenced in explorers.

![image](https://user-images.githubusercontent.com/2641501/154525281-77c24374-b2e4-4d3b-8489-779c450b4a07.png)

## Alternatives

It might also make sense to integrate this into the `owid-analytics` workflow, or into Datasette.

If there are current plans to persist the OWID content graph on disk, then we could also add an additional content graph for the SDG Tracker so that both content graphs can feed the References tab.

## Context

Suggested solution:

### For the SDG Tracker:
1. Source the https://github.com/owid/sdg-tracker.org repo and look for all occurrences of the form
	  * `<a href="https://ourworldindata.org/grapher/SLUG">`
	  * `<iframe src="https://ourworldindata.org/grapher/SLUG">`
2. Resolve the slugs into grapher ids (beware of redirects!)
3. Store them into a JSON file of references
4. do this all in a cron job or so

### For explorers:
1. On save of an explorer, run a script over the https://github.com/owid/owid-content repo that instantiates all `graphers` tables
2. Keep track of the chart ids used in the `grapherId` column (if present)
3. Store them into a JSON file of references

**Comment by MarcelGerber** [comment]
Related to the owid/owid-issues#98 work.

**Comment by mlbrgl** [comment]
Persisting the content graph on disk was one of the angles I explored to get very fast prominent links lookups, even for post previews (otherwise, you would need to generate the graph on every preview, which is an additional 10 - 20s).

Fortune.js comes with a [filesystem adapter](https://github.com/fortunejs/fortune-fs), which is a simple drop-in replacement for the default in-memory adapter. It works as expected, but is obviously slower. That led me to consider moving the graph to Redis. At that point, it started to feel like a project of its own, so I dropped it.  There was also concerns about adding an extra tech to our stack.

Another angle that has been mentioned a few times is persisting the relationships in MySQL.

The workflow I was landing on was generating a fresh content graph on every bake, then consume it in between bakes in read-only mode. The downside is that the content graph would be slightly outdated at times, which I found acceptable given the timeframe and use case considered.

Beyond prominent links, the references tab was indeed in my mind as a component that would greatly benefit from not having to compute those relationships on the fly every time. I think this makes a lot of sense.

One thing to keep an eye on if we were to slow down the existing content graph lookups is the performance of the grapher pages, which consume it.

I'm not-so-loosely planning on pickup that up at some point, but not in the next few weeks.

**Comment by marcelgerber** [comment]
@bnjmacdonald has asked for a refresh of the (list of unused charts)[https://github.com/owid/owid-issues/issues/98].
In my eyes, it makes sense to build this up into a scalable solution and start out with the content graph.

What's still to be decided is whether we want to build this into the admin, into Datasette, or someplace else.
