### ISSUE TITLE
Only keep the most important metrics on country profiles

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1236]
## Core problem

We believe we're getting a lot more attention on our country profiles, especially the profile for Ukraine, right now. (unverified)

But our profiles are not really something that we're happy with the quality of, and they point to data that is quite old and not updated.

## Proposed solution

We think we can make them better by reducing the metrics shown to just metrics that are used in one or more articles on our site.

We get critiqued for what is or isn't included, so we will probably need to update our text to explain what the list is: "Below are all indicators in our database mentioned in any of our articles"

## Alternatives

We could alternatively just list World Development Indicators for each country.

## Context

Requested by @maxroser 

We'd like to do it quickly, but only if it's as easy as expected to fix.

**Comment by danielgavrilov** [comment]
## Todo

- [ ] Figure out the "most important metrics" are – ask authors for help on this? Maybe an `owid-issues` issue:
    
   > To improve country profiles (https://github.com/owid/owid-grapher/issues/1236) we need to first figure out what the "most important metrics" are. We think 20-50 metrics would be best. 
   >
   > We could use the energy/co2/coronavirus templates to redesign the existing country profiles, for example: https://ourworldindata.org/country/germany
   >
   > Currently, the country profiles look like this: https://ourworldindata.org/country/germany

**Comment by larsyencken** [comment]
@danielgavrilov It was probably not clear in our chat about this, but the feedback we already had from authors was on what to include was baked into the original description of the issue, i.e. to limit to just the charts we mention in articles, or if that is difficult, just include World Development Indicators.

If we also cut design changes out of scope, then this becomes a short, filtering exercise rather than a longer discussion.

**Comment by marcelgerber** [comment]
A draft PR is now over at #1320.

Interestingly, it increases the number of available indicators rather than decreasing it, even though we are now only displaying the charts that are embedded in at least one page.
That's because we were wrongly excluding some charts that should've been included before (https://github.com/owid/owid-grapher/commit/b3849bb116bcb5abb1b4782b32995f3ffd4063d4).

Whereas we currently have 353 indicators on [Ukraine (live)](https://ourworldindata.org/country/ukraine), we now have 503 on [Ukraine (tufte)](https://tufte-owid.netlify.app/country/ukraine).
In addition, we're _still_ excluding some important charts because the country profiles only include line charts with exactly one dimension, which means that important charts like [Causes of death](https://ourworldindata.org/grapher/annual-number-of-deaths-by-cause) are not shown at all.

## For discussion

Seeing this, it's probably sensible to go with another way of limiting indicators, e.g. by having a predefined list of OMMs like we discussed above. What do you think @larsyencken?

**Comment by larsyencken** [comment]
Thanks for investigating Marcel! How would it look if we restricted to the world development indicators dataset?

If that doesn't look promising, then I think we'd shelve this for now and wait for a redesign of the country profiles to decide how we want there.

**Comment by larsyencken** [comment]
Thanks Marcel. I think that based on your investigations here, we'll close the issue without merging and wait for a bigger redesign of country pages later in the year. It's still progress to learn that these options weren't better than what we have.

**Comment by larsyencken** [comment]
@maxroser Just a heads up that in our investigation of country pages, making them better by just picking different metrics to show was not at all easy or a quick fix. I'm deferring further changes until we have a better design.
