### ISSUE TITLE
Refactor grapher selection and deprecate selection by id

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1245]
## Core problem

The grapher config currently has 3 selection related fields: `selectedEntityNames`, `selectedEntityIds` and `selectedEntityColors`. The Daniels discussed this a bit and here are some of the current thoughts around this project:

* We should refactor the config to use one array of an object for selections instead of the current 3. This array should hold objects that should probably have the entity code or as a fallback the entity name and an optional entityColor. The color is used for line charts etc to color entities.
* We want to move away from entity ids. In a world where we stop putting all the data into MySQL and we have a data catalog instead, we will have either harmonized dimensions like countries/regions or sex, or non-harmonized ones (e.g. fish species). Harmonized dimensions will have codes for most entities. Non-harmonized or super unusual entities in otherwise harmonized dimensions will use the the name. This is already how query string selection serialization works
* This should either directly fix a few related issues or make the fixes for those more straight forward
* It will also make editing selections in the bulk FASTT editor possible without weird hacks

Somewhat optional we could also do this at the same time:

* Drop the typescript file mapping countries to continents and make grapher consume our countries_regions.csv instead

## Scope

- [ ] Propose a new selection format that includes names and colours
- [ ] Implement the new format alongside existing selection
- [ ] Update admin interactions to use new selection
- [ ] Do a mass migration of existing charts to the new format (incl. QA)
- [ ] Deprecate and remove old selection code

**Comment by danyx23** [comment]
#1111 is related to this issue

**Comment by danielgavrilov** [comment]
Agree with the above! 

Also related and "somewhat optional" is that we should move away from:

- Storing entity codes in our codebase: https://github.com/owid/owid-grapher/blob/6a5729d34556a241bbc38b0c1cf72e105c6af3a2/grapher/core/EntityCodes.ts#L4-L294

- Storing population numbers in our codebase: https://github.com/owid/owid-grapher/blob/543a1448218fdb6342ebcfca2f32c8a87376a4d2/coreTable/PopulationMap.ts#L2-L283

**Comment by marcelgerber** [comment]
Agreed! That's a whole new world one can only dream of ❤️

**Comment by marcelgerber** [comment]
Just chatted with @danyx23 about this.

We came up with the idea that we want to assign an entity code to every entity, and use that one throughout.
For countries, we will naturally continue using the existing 3-letter codes, and same for `OWID_WRL` etc.
For other, more one-off entities, we can auto-generate a slug from the entity name, and use that for the entity code. E.g. `Sint Maarten (Dutch part)` -> `sint-maarten-dutch-part`.

Pro:
* Currently, our entity names can contain many weird symbols, like commas, semicolons, quotes, parens etc. Basically the only character that they _should_ not contain is a tilde (which we use to separate entities in the URL string), but we never enforce this.
* Using this, we have a way more restricted set of characters that we need to include in the URL for entity selection.

Caveat:
* We would need to ensure the uniqueness of entity codes, since obviously `Sint Maarten, Dutch Part` and `Sint Maarten (Dutch Part)` would map to the slug. Same for uppercase/lowercase differences.

**Comment by marcelgerber** [comment]
More selection madness: We currently have 36 charts that contain at least one `selectedEntityName` of `null`. E.g. https://ourworldindata.org/grapher/decadal-deaths-disasters-type has `selectedEntityNames: ["World", null]`.

<details>


```sql
SELECT config->"$.selectedEntityNames"
FROM charts
WHERE config->"$.selectedEntityNames" LIKE "%null%"
```

</details>

**Comment by marcelgerber** [comment]
We talked about this in today's grapher hour.

Some of the problems and weirdnesses we have:
- Legacy charts are using `selectedEntityIds` in their config, new ones are using `selectedEntityNames` (which is preferred over `selectedEntityIds`)
- Some `selectedEntityNames` objects contain `null` (#1819)

We would like the default selection object to look something like this:
```js
selection: [
	{ entityCode: "IRN", color: "#ff0000" },
	{ entityCode: "FRA", color: "#babcde" },
	{ entityName: "High-income countries" }
]
```

**Comment by marcelgerber** [comment]
In #2101, I got completely rid of the `selectedEntityIds` field, so that there's only `selectedEntityColors` and `selectedEntityNames` left.
So, we're in a better state now, but still not in the dream state we imagined above where color and entity information is combined in an object.

**Comment by danyx23** [comment]
@marcelgerber did most of this already. We still have the somewhat weird configuration of selected entity colors but we think it makes more sense to think about this when we normalize selection/highlighting behaviour across charts.
