### ISSUE TITLE
When deleting a chart, create an automatic redirect

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1247]
## Core problem

Authors delete a lot of charts now during cleanup. Unless they manually create a redirect for the former URL, this leads to 404 errors for visitors coming to this page via an external link.

## Proposed solution

Max proposed that when available, the content the chart was tagged with or the origin url should be set up as redirect targets automatcially for charts when they are deleted. This would lead audiences at least to very related content instead of a 404 page.

## Context

A short slack thread on this issue is [this one](https://owid.slack.com/archives/C0149NKLZAM/p1646409277636949).

**Comment by danielgavrilov** [comment]
I don't think automatically redirecting to the origin URL is a good idea, or _automatically_ redirecting to anything really. It **should be the explicit decision of the author** what the best redirect is. If we automatically redirect, it becomes harder to track broken links (we effectively sweep them under the carpet by not having a 404). 

**Since our charts are often embedded, the best redirect is another chart, not an entry.** 

Potentially we could also introduce an "archived" stage of charts, where they have a notice over them that they are out of date, and a suggested URL for more up to date content.

**Comment by danielgavrilov** [comment]
Yes, we probably have to think/discuss. To brain dump a bit:

Currently we are creating 404s when deleting, and 404s are reviewed periodically (by Charlie). So deleting a (popular) chart will show up as a to-fix task for Charlie when he reviews 404s. Then he has to infer based on the URL what the right redirect should be.

One thing we probably should do is never completely delete charts from the database, only mark them as deleted with a boolean flag. (I was looking into this some time ago, MySQL's lack of partial indexes makes it a bit harder to implement, because we want to disable some integrity checks for deleted charts.)

Having an archived status with an optional entry/chart URL might give authors a good alternative to deletion, which is a destructive and non-reversible action. I am guessing the decision to archive would be easier than to delete.
