### ISSUE TITLE
Allow for entering multiline strings in the explorer config

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1329]
## Description

Footer text sometimes overflows into timeline, likely height miscalculation in header or footer. Examples:

- https://ourworldindata.org/grapher/share-of-working-children-who-work-only
- https://ourworldindata.org/explorers/fish-stocks

<img width="966" alt="Screenshot 2022-03-29 at 14 42 59" src="https://user-images.githubusercontent.com/1308115/160625148-4dc287ef-e4dd-4819-a3c4-c34ac8821731.png">

## Expected behaviour

Footer text shouldn't overflow.

**Comment by larsyencken** [comment]
Estimated as not more than 1d. Seems like a bounding box has an incorrect height, which is messing up the calculations.

**Comment by marcelgerber** [comment]
Okay, this one is relatively simple. The explorer config contains `<br>`s, which we don't support.
https://github.com/owid/owid-content/blob/a9c513fbe204d34da331bc78d282107455a1882f/explorers/fish-stocks.explorer.tsv#L14

They are output as raw HTML in the subtitle, but are not taken into consideration in the header height calculation. They also don't work in the png/svg exports:
![image](https://user-images.githubusercontent.com/2641501/166220249-93c441db-f26f-4788-b75e-687f72fe552f.png)

---

The issue becomes a different one then: Add a supported way to add a newline in the explorer config, because there is currently no such feature.

**Comment by marcelgerber** [comment]
From now on, newlines in subtitles, notes etc. can be entered in Handsontable by pressing `Ctrl + Enter` in the field editor.
Alternatively, one can also put `\n` into the field directly.
