### ISSUE TITLE
Error in setting up container

### ISSUE THREAD

**Issue by amritesh19** [owid/owid-grapher#1374]
### Discussed in https://github.com/owid/owid-grapher/discussions/1373

<div type='discussions-op-text'>

<sup>Originally posted by **amritesh19** April 10, 2022</sup>
Hi, I am trying to setup development environment within VS Code devcontainer, but encountering this error. 

![image](https://user-images.githubusercontent.com/73696688/162587109-78a59100-163d-4118-a8cd-d05438e3cbc2.png)
![image](https://user-images.githubusercontent.com/73696688/162587165-64476cc3-c1e3-485c-8fbb-3385cb2275f1.png)

Please help me resolve this.
</div>

**Comment by danyx23** [comment]
Hi @amritesh19! Can you tell us what OS you are running? Do you have docker installed? Can you run `docker ps` in a terminal and if so what is the output?

**Comment by amritesh19** [comment]
Thanks @danyx23 for replying. I am using Windows 10 with WSL2. Yes, I have docker installed in my machine. After running `docker ps` , the output is following: 
![image](https://user-images.githubusercontent.com/73696688/163236257-2ec9de6a-f344-48f2-b5fd-8f313d853314.png)

**Comment by danyx23** [comment]
Yes there were some issues due to the recent simplifications. Can you update to the latest version of the codebase, remove your .env file and run the new make command described in the [devcontainer setup docs](https://github.com/owid/owid-grapher/blob/master/docs/devcontainer-setup.md)? As you are on windows you may also have to [follow the instructions for git on windows](https://github.com/owid/owid-grapher/blob/master/docs/before-you-start-on-windows.md) to make sure that the line endings are not automatically converted which causes issues with the scripts for loading the database etc.

**Comment by amritesh19** [comment]
@danyx23 I have ran those git commands, tried removing .env files, but still same error persists. I am not able to run make command as terminal is not allowing to write without completing devcontainer initial setup.

**Comment by r3h0** [comment]
@amritesh19, can you share the full stack trace? In both screenshots, it appears to be cut off.

**Comment by larsyencken** [comment]
I hope you managed to get it working! Since we haven't heard more, I'm closing the issue for now.
