### ISSUE TITLE
CMS: Charts appear next to subtitle on blog posts

### ISSUE THREAD

**Issue by HannahRitchie** [owid/owid-grapher#1387]
## Description

On posts, charts in the right-hand column bubble up next to the excerpt/subtitle. They should only start next to the main text.

## Expected behaviour

I would expect that the chart shows in the column next to the main text. Instead, it appears higher – right next to the subtitle.

## Steps to reproduce

https://ourworldindata.org/where-does-plastic-accumulate

## Screenshots

<img width="1408" alt="Screenshot 2022-04-13 at 15 12 48" src="https://user-images.githubusercontent.com/35040753/163200161-369b6c6a-b0dd-432b-a63b-fd6a84e06f0a.png">

**Comment by mlbrgl** [comment]
This is actually the expected behaviour, it was designed this way to give access to the data as early as possible in the page
<img width="934" alt="Screenshot 2021-11-23 at 18 43 31" src="https://user-images.githubusercontent.com/13406362/163584204-5d3611d2-da67-495f-a4ba-24e2b04501bc.png">

Context:
- [task](https://www.notion.so/owid/Simplify-article-header-ca187184ec5e45eabcbf8a5f0f51523d#9985daa6cb7547a9af2c8fee26bc33f9)
- [project](https://www.notion.so/owid/Shorts-v2-4cbcca4daca247af84d2d4d5602d7a69)
- [specs](https://www.notion.so/owid/New-header-for-posts-and-shorts-6be4f2aa60d24974aa908bfbb97c0051)
- [figma](https://www.figma.com/proto/ZqIQ6UkPi9tGMiPK6i78fW/Shorts-%26-new-entries?page-id=0%3A1&node-id=130%3A7002&viewport=337%2C48%2C0.39&scaling=min-zoom&starting-point-node-id=130%3A7002)

**Comment by danyx23** [comment]
@HannahRitchie it's not clear how we can improve this without making shorts worse (where it was requested as @mlbrgl mentions). Do you have an instinct of when you want the push up behaviour and when you don't? Is this bad enough to invest time in?

**Comment by larsyencken** [comment]
Closing as "wontfix" for now, but flagging it with Marwa so she's aware of it.
