### ISSUE TITLE
Updating the dimensions on Admin "Basic" tab is slow and blocks the UI

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1388]
## Description

Ed reported this in [slack](https://owid.slack.com/archives/C46U9LXRR/p1649854101035369) in April and recently Pablo and Fiona reported it again in August in [slack ](https://owid.slack.com/archives/C46U9LXRR/p1660895841098999)- a lot of "harmless" interactions on the basic panel seem to trigger calls to [updateLegacySelectionAndRebuildTable](https://github.com/owid/owid-grapher/blob/4dd1cd71915b51b0ee009e98009e0c572dbc06eb/adminSiteClient/EditorBasicTab.tsx#L153). This causes a new download, a block of the admin UI and a potentially expensive join operation (Ed's example was for [chart 2904](https://owid.cloud/admin/charts/2904/edit) where this takes a few seconds).

In some cases reordering (the ones found by Pablo and Fiona) creates non-deterministic reorders that make it very hard to make changes to the variables you want to (meaning this is no longer just a performance issue but now a big UX issue).

As @danielgavrilov writes below, the root cause of this is the dimensions array being re-ordered. Nowadays Grapher works with table columns but dimensions are still updated and then trigger the legacy -> table columns transformation. It probably makes sense to tackle this together with #1245 

## Expected behaviour

As long as the variable id and order (am I forgetting anything?) stay the same, interactions in the basic panel should complete immediately without any superfluous downloading, joining. 

Also, unfolding a variable should never open another variable or change ordering.

## Steps to reproduce

Steps to reproduce the horrible UX issue:

1. Go to the [chart 4675](https://owid.cloud/admin/charts/4675/edit) admin UI
2. Unfold a variable in the basic tab
3. Watch the variables jump in order and open a different variable
4. Try editing values and despair

Steps to reproduce the performance behavior:

1. Go to the [chart 2904](https://owid.cloud/admin/charts/2904/edit) admin UI
5. Unfold a variable in the basic tab
6. Wait and hear your laptop fan spin up
7. Despair

The flame graph section below is 6 seconds:

![flame-graph-talbe-joins](https://user-images.githubusercontent.com/2772449/163223437-ded67a58-d151-44f6-ab72-d3cbbe0af397.png)

**Comment by danielgavrilov** [comment]
> I think this comes from doing this hacky drag and drop that we use in a few places.

The drag and drop is hacky, but the bigger issue I think is that there is a "legacy" dimension config stored in the database, and it gets transformed into a new "column" config. When making changes to the legacy, we need to re-run a bunch of transformations.

I think the fix for that is to migrate to using the new "column" config for dimensions.

**Comment by marcelgerber** [comment]
> I think the fix for that is to migrate to using the new "column" config for dimensions?

Agreed! I think that would be part of #1245, right?

But we should leave switching out the DnD implementation as a stretch goal; there's some very sketchy code in our drag-and-drop support.

**Comment by danielgavrilov** [comment]
Some more context: I think, but haven't tested, that the bulk of the issue is that the `table` component, with all data, gets recreated whenever the `dimensions` are updated. This means _every_ table transformation has to be re-run, including constructing the table.

The tolerance changes will affect this code, but potentially for the worse, since we need more complex joins in the table construction... So maybe then the problem gets worse, and maybe that makes the tolerance task balloon even more. 

So anyway, not much happy news.

**Comment by danyx23** [comment]
Reopening this (and updated the description) after Pablo and Fiona raised some horrible UX issues around this: https://owid.slack.com/archives/C46U9LXRR/p1660895841098999 and https://owid.slack.com/archives/C46U9LXRR/p1660913285616899

**Comment by danyx23** [comment]
Suggesting Prio 2 now but also added needs-triage to decide this together with @larsyencken

**Comment by danyx23** [comment]
This SQL query is an approximation of charts that are affected by the issue found by Pablo and Fiona. There might be more but the ones here seem to have the issue described:
```sql
WITH config_with_lengths as
(
select
	id,
	json_length(config,'$.dimensions') as dimensionsCount,
	json_length(config,'$.selectedData') as selectedDataCount,
	
        config->>'$.type' as type,
	config->>'$.selectedData' as selectedData,
	config->>'$.selectedEntityIds' as selectedEntityIds
from
	charts )
select
	*
from
	config_with_lengths
where
	dimensionsCount > 1
	and 
	(dimensionsCount > selectedDataCount
		and selectedDataCount > 0)
	and type not in ('ScatterPlot', 'TimeScatter')
order by
	id asc
```

**Comment by marcelgerber** [comment]
An analysis together with @danielgavrilov and @danyx23 showed that we really have a multitude of problems here:

### The heavy `onMouseUp` handler is firing every time the mouse button is released.

Even when it's only the expand/collapse button that is being clicked. The `updateLegacySelectionAndRebuildTable()` in particular is the heavy operation being run here.

https://github.com/owid/owid-grapher/blob/5298444d29cc4fa7caf8a377bed33f698313306e/adminSiteClient/EditorBasicTab.tsx#L149-L154

### `dimensionsOrderedAsInPersistedSelection` trips up.

The `dimensionsOrderedAsInPersistedSelection` method attempts to display the variables in the same order as they would appear in the chart.
However, this trips up in case
* `dimensions.length != selectedData.length`
* `map(selectedData, (item) => item.index) != range(0, dimensions.length)`, i.e. the indices in `selectedData` are not in ascending-by-one order

In particular, it trips up because `legacyConfig.dimensions` is being changed in every call to `updateLegacySelectionAndRebuildTable`, and then picking them out by index results in a different order each time. This is the main cause for the dimensions jumping around in the list of dimensions.

https://github.com/owid/owid-grapher/blob/5298444d29cc4fa7caf8a377bed33f698313306e/grapher/chart/DimensionSlot.ts#L46-L59

### Ignoring newly added dimensions if `selectedData` is present.

`selectedData` is a legacy property and is not really being written to any longer.
However, it is still present in basically all our charts authored before Project Next.
If one such chart is being edited to add a new variable/dimension now, there is a good chance that the variable will not show up in the chart.
That's because there is code that uses `selectedData` to pick out dimensions by the indices (and in the order) specified by `selectedData`.

https://github.com/owid/owid-grapher/blob/5298444d29cc4fa7caf8a377bed33f698313306e/grapher/core/Grapher.tsx#L2036-L2055

**Comment by marcelgerber** [comment]
Currently, `selectedData` is still being used to (in legacy charts):
* select variables to show
* select entities to show by default
* specify the order of dimensions
* specify colors for dimensions

There are several ways to go forward, and we haven't decided yet:
* Write a DB migration that completely gets rid of `selectedData`, and incorporates everything that is currently saved in there into the non-legacy config fields (`dimensions` in particular).
  This is a lot of effort, but might also be the most sane option and will let us get rid of quite a bit of legacy code.
* Write a transformation that runs very early.
  Currently we have several transformations that touch `selectedData`, both in the Admin and the Grapher.
  Instead, we can run one piece of code that transforms the config very early on - before the Admin or Grapher ever see it - and then drops `selectedData`. However, there is not much advantage over a DB migration I think?
* Drop all `selectedData` entries from the config and see what happens 🤷🏻 
  Some charts will lose column colors, default entities, and especially stacked charts will be reordered. But it might be an okayish number of affected charts that we can catch using the SVG tester, and that we can then manually change.
  
  Important note: To find all changes we would need to get a svg version of every Chart tab, even for charts that default to the Map tab.
