### ISSUE TITLE
Add citation information to articles

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1484]
_[Original issue](https://docs.google.com/spreadsheets/d/1pzDLxB7TalliYVrO3JctbuKjkgK1tm9J5kwxrWdtBsU/edit#gid=660478851) by @maxroser_

## Core problem

Readers don't know how to cite articles.

## Proposed solution

Derive citation information from the article parent topic.
Requires articles and topics to be linked through [parent <-> child relationships](https://www.notion.so/owid/Knowledge-graph-entries-as-topics-unify-grapher-and-Wordpress-taxonomies-4992c4f2671248c8872e19073debb172), deployed in #1070 and built upon in #1447

## Context

- https://www.notion.so/owid/Sync-last-updated-date-with-citation-c6ce6a725c4445aeb2430a6a643a2c0f
- https://github.com/owid/owid-issues/issues/266

**Comment by maxroser** [comment]
Good reminder by the GitHub bot! We also just discussed it yesterday and it'd be good to make progress on this one.

cc @mathisonian and @JoeHasell

**Comment by danyx23** [comment]
@JoeHasell should we close this issue? Should we update it to reflect our thinking?

**Comment by ikesau** [comment]
We still want to tweak citations, see the most up-to-date thinking on this issue is https://github.com/owid/owid-issues/issues/1277

So for example, https://ourworldindata.org/safest-sources-of-energy is tagged "Energy" so we would like its citation name to be `owid-energy` instead of `owid-safest-sources-of-energy`

![image](https://github.com/user-attachments/assets/8fc31e3f-76de-49ad-90f0-b4a13b7249ff)


Once https://github.com/owid/owid-grapher/tree/sitenav-from-tag-graph is merged and the tag graph is harmonized with our current taxonomy, we'll be able to make moves on this.

**Comment by ikesau** [comment]
Google Scholar isn't going to be able to understand this concept of "volumes" that we were thinking about earlier this year, so the tag graph-derived citations idea is DOA.

We'll wait and see if citation confusion comes up again.
