### ISSUE TITLE
Grapher share link might be unnecessary long

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#1655]
## Description

When copying the share link from [this chart](https://ourworldindata.org/grapher/world-regions-sdg-united-nations?region=NorthAmerica&country=LTU~SWE~ARG~MCO~UKR~JAM~COL~WLF), I get an unnecessary long link: https://ourworldindata.org/grapher/world-regions-sdg-united-nations?region=NorthAmerica&country=LTU~SWE~ARG~MCO~UKR~JAM~COL~WLF (as it shows countries, when I believe it is not needed?).

## Expected behaviour

The link should be shorter, e.g.: https://ourworldindata.org/grapher/world-regions-sdg.-united-nations?region=NorthAmerica

## Steps to reproduce

1. Go to this https://ourworldindata.org/grapher/world-regions-sdg-united-nations
2. Select "North America" view
3. Click on the share button in the bottom chart nav bar, then on "Copy link"
4. Now you have the "wrong" link

**Comment by larsyencken** [comment]
Thanks for reporting Lucas! In this case, we prefer the links to be over-specified, since the GET parameters are a partial chart config, and we might want to change the settings of that chart on our site without breaking any embeds that already use it.

Unfortunately, we don't have enough information about how embeds are being used to help us steer these things well. But probably we'll leave this as it is for now. Marking as "wontfix".
