### ISSUE TITLE
Extra margins around one of the bars in stacked bar charts

### ISSUE THREAD

**Issue by edomt** [owid/owid-grapher#1679]
## Description

One of the bars (`Rice`) in this stacked bar chart has extra margins on the top and bottom.

## Steps to reproduce

https://ourworldindata.org/explorers/food-footprints?facet=none&country=Almonds~Bacon~Bananas~Rice~Beans~Beefburger~Pizza~Cow%27s+milk~Penne+pasta~Vegetable+lasagne~Tofu~Steak+pie~Beef+%28beef+herd%29~Lamb+%26+Mutton~Beef+%28dairy+herd%29~Prawns+%28farmed%29~Cheese~Pig+Meat~Poultry+Meat~Eggs~Rice~Tofu~Milk~Tomatoes~Maize~Wheat+%26+Rye~Peas&Commodity+or+Specific+Food+Product=Commodity&Environmental+Impact=Carbon+footprint&Kilogram+%2F+Protein+%2F+Calories=Per+kilogram&By+stage+of+supply+chain=true

## Screenshots

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/7103774/191998165-cd92aad3-6b65-4320-94ff-44bbcbd59db0.png">

## Environment

MacOS Firefox 104.0.2

**Comment by marcelgerber** [comment]
Fixed now. The problem here was that `Rice` and `Tofu` were duplicated in the default selection of the explorer, see https://github.com/owid/owid-content/commit/af723c209db7fa2058e6960dba902e2656527abe.

This is an authoring issue, but if it happens more often, then we can deduplicate the selection in code.
