### ISSUE TITLE
Anchor links on "All Charts" page are removed on pageload

### ISSUE THREAD

**Issue by mathisonian** [owid/owid-grapher#1680]
## Description

When navigating to an anchor link like https://ourworldindata.org/charts#research-development on the all charts page, the anchor is removed and the page does not scroll to the right location.

## Expected behavior

The page scrolls to the area specified by the anchor 

## Steps to reproduce

1. Go to this URL https://ourworldindata.org/charts#research-development

## Environment

For desktop, provide:

-   OS: MacOS
-   Browser: Chrome
-   Version 105

**Comment by ikesau** [comment]
This is caused by the [search bar renderer overriding the URL when it runs.](https://github.com/owid/owid-grapher/blob/master/site/runChartsIndexPage.ts#L85-L90)

Concatenating `window.location.hash` to the final argument of the `replaceState` will be necessary.

The other issue is that the [Search input has an autofocus](https://github.com/owid/owid-grapher/blob/master/site/ChartsIndexPage.tsx#L107), which means that the anchor link won't get navigated to, even if it's in the URL, because the browser will always navigate to the search bar at the top of the page.

We need to decide what we want to have happen when there's an anchor link and a search query in the URL.

1. Always autofocus search bar (i.e. anchor links on page load would be useless)
2. Only autofocus if search query is present (i.e. anchor links would work on page load as long as no search is set)
3. Never autofocus (i.e. anchor links would work on page load as long as the relevant heading hasn't been filtered by a search)

I think option 3 is best.

**Comment by mathisonian** [comment]
Ah nice, thanks @ikesau. 

That fix for the `replaceState` call makes sense. 

What about having autofocus on for search unless an anchor tag is present? That way we keep the current behavior (which seems nice for quick searches) unless you've explicitly linked to an anchor. If that doesn't work for some reason option 3 would work.

**Comment by ikesau** [comment]
Whoops I forgot to fill out my quadrants 😄 

I'm not a fan of autofocus as it takes control away from the user by immediately opening a keyboard for mobile users, or hijacking screen readers to immediately narrate the input context as opposed to the page.

That's more of a general principle, though. One could argue that autofocus is better and more convenient in this instance.

The other thing is that conditionally auto-focusing is slightly trickier because of SSR. It's definitely easier to just disable it completely.

Up to you.

**Comment by mathisonian** [comment]
Okay, those are good arguments 👍 I'm fine to disable it
