### ISSUE TITLE
Replace "Entry" with "Topic" in search results

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1829]
## Context
Entries become Topic pages across the site.

## Proposed solution

Rename "Entry" by "Topic" in search result pages, e.g. https://ourworldindata.org/search?q=trade

<img width="527" alt="Screenshot 2022-12-16 at 15 31 57" src="https://user-images.githubusercontent.com/13406362/208381832-7aa3c72d-8ec1-46ac-bc3f-aa11d902a60c.png">

As part of this issue we also need to make sure that topic pages and old style entries are both indexed as the same thing in Algolia and that our own custom importance score is high (3) for both.

**Comment by devgarg2000** [comment]
Hey, let me know if I can contribute to make the correction. Seems quite doable to me.

**Comment by ikesau** [comment]
Hey @devgarg2000 thanks for you interest, we've looked into this family of issues slightly more and realized that it's going to require some more advanced configuration of our Algolia indexing. It's probably not a great first issue anymore 😅 

For triage purposes, we're going to check with @marcelgerber during the Algolia knowledge transfer next week to get a better handle on what's required here.

There's also a question for @JoeHasell - are we ready to call _all_ (old style) Entries and Topic Pages _Topic Pages_? Specifically this issue is for search results, but once we make the change here we'd probably want to make the change everywhere else.

**Comment by JoeHasell** [comment]
Hey @ikesau – yes we're happy to call all (old style) Entries and Topic Pages 'Topic Pages'. (The consensus was that 'Old style Entry' remains a helpful internal term to discuss the transition, but that it's confusing to keep the term 'Entry' in circulation on the website.).

**Comment by marcelgerber** [comment]
It currently looks like we're lacking a good way to programmatically detect that a certain page is a topic page.
It used to be the case that all old-style Entries had the "Entries" tag applied, and that was how we identified them. But that's currently not the case for new topic pages like `/poverty`.

Similarly, the `importance` attribute in Algolia is also based on whether a page is a topic page, and that's the main factor in ranking a page highly. So we should also adapt that logic once we know how to identify topic pages ;)

**Comment by mlbrgl** [comment]
I think it has just be forgotten. Let me check with authors: https://owid.slack.com/archives/C03NV9Z3YSV/p1673613179373189
