### ISSUE TITLE
Navigation menu redesign

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1874]
<img width="805" alt="Screenshot 2023-01-24 at 15 46 51" src="https://user-images.githubusercontent.com/13406362/214295516-ea059508-c051-42cf-a16d-f14a5bd6e3ed.png">

🎨  [Figma](https://www.figma.com/file/9bQW46okOjxeJtismQQdPu/%5BDesktop%5D-Screens-1.0?node-id=3117%3A28509&t=gDKatPiTtPhjqWFt-0)

**Comment by larsyencken** [comment]
Just throwing out an idea: seems like it could be helpful to both alphabetise the subtopics for easy scanning, but also to somehow identify major pages and bold them in the list so that they stand out.

If we were _extremely_ lazy, we would use the 30d pageview counts that Marcel will add to MySQL this cycle, and bold the top 5 subtopics in each topic area by pageview count.

**Comment by mlbrgl** [comment]
We probably need to check with authors since the sorting of these categories is done manually by them (although ordering is broken at the moment, see #1896). 

I would be tempted to leave this to another phase of the navigation refactor (beyond this reskin), maybe post Wordpress migration since we'll have to rebuild the taxonomy off WP anyway.
