### ISSUE TITLE
Map chart has segments of uneven width when hovering over countries

### ISSUE THREAD

**Issue by YannyTwoo** [owid/owid-grapher#1886]
## Description
(Not sure if this even counts as an issue, since this doesn't seem to be a bug on the actual OWID site, but thought I'd bring this to attention)

The highlighted borders of countries when hovering over them on the map chart have a thinner width with some countries and a thicker(normal expected width) border with other countries and the sea.

<img width="334" alt="ss" src="https://user-images.githubusercontent.com/79789927/215589877-ba441bf7-5b73-4900-b5c1-a6b9f350b0e8.png">
<img width="514" alt="ss2" src="https://user-images.githubusercontent.com/79789927/215589897-ce764e13-38c9-49ac-93af-ef89b7182c91.png">

Interestingly this isn't an issue on the actual site...
Only when viewing the components in storyblocks

The screenshots below are from the OWID site(All borders of constant width)

<img width="351" alt="ss3" src="https://user-images.githubusercontent.com/79789927/215590121-c14da5c7-688f-40b1-873f-ebad4ec29266.png">
<img width="366" alt="ss4" src="https://user-images.githubusercontent.com/79789927/215590141-c89f9d3e-6e7e-4175-b69c-e68d0840f604.png">
<img width="351" alt="ss5" src="https://user-images.githubusercontent.com/79789927/215590152-5c595e72-c912-4436-b7ef-e6b6c997966e.png">

## Expected behaviour

As mentioned this isn't an issue on the actual site itself.

## Steps to reproduce

1. Locally setup the owid-grapher repo
2. Open the storybook UI 
3. See map chart under CaptionedChart
4. Hover over the countries the discrepancy should be visible

## Environment

-   Chrome
-   Version 108

**Comment by marcelgerber** [comment]
Yes, I can go into a little bit of detail as to why this happens.

In map charts, every country is a separate SVG path, with a border ("strokeWidth" etc.) for its outline. For neighboring countries, the country outlines overlap a bit.
Since the browser renders the paths in the order they appear in the DOM. In your negative example above, it seems that we draw China _before_ Mongolia, which then means that Mongolia's normal-width outline overlaps the wide China outline, and the effective China outline is only (roughly) half as wide where it's bordering Mongolia.
I hope that makes sense.

We have code in place that is meant to avoid this issue, in particular this [sortBy call in MapChart.tsx](https://github.com/owid/owid-grapher/blob/0a69c533ab866fd2699f98da4989fab2297ebde8/packages/%40ourworldindata/grapher/src/mapCharts/MapChart.tsx#L982-L983). It's very long, but roughly:
```tsx
sortBy(mapFeatures.map(toPath), path => path.strokeWidth)
```

This makes it so that highlighted (wide-border) countries always appear last in the DOM, where no neighbouring country can interfere.

As you say, this seems to be working fine on the site itself. As to why it doesn't work well in Storybook, that I don't know. But if you want to go down that rabbit hole, you should now be well-equipped to find out.

Hope this helps!

**Comment by ikesau** [comment]
Hey @YannyTwoo thank you for the well-formatted issue submission. If you would like to look into what's causing this in Storybooks, feel free, however I'm going to close this issue as a #wontfix for us. 👍

**Comment by YannyTwoo** [comment]
Sure 👍🏻
