### ISSUE TITLE
Index gdocs articles in Algolia

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1894]
## Core problem

Indexing articles currently relies on the Wordpress API. Any article that'll be going through the gdocs pipeline won't get indexed and surfaced in search.

## Proposed solution

Go through published gdocs articles and index them with the usual paragraph splitting procedure.

Extracting structured information (e.g. key insights) from the Archie JSON is considered out of scope, but a good candidate for a follow-up to further feed the search content graph.

## Context

This was part of the "Additional scope" of #1613

**Comment by danyx23** [comment]
@mlbrgl @marcelgerber what do you think would be the best format to index into Algolia? Plaintext? Html? Do you have a sense for how much work this will be?

**Comment by marcelgerber** [comment]
so, the output format that we will need to have in Algolia is plaintext, it can't handle anything else than that.

I know little about how the gdocs pipeline is built up now, but in general there are two ways:
- Have some gdoc -> plaintext pipeline that is specific to the different blocks in the gdoc
- Convert gdoc -> HTML as usual, and then use `text2html` to convert that to some text representation. This is what we're doing now: https://github.com/owid/owid-grapher/blob/558353056d8f539b528b1e7ba406d54b5f2a2186/baker/algolia/indexToAlgolia.ts#L72-L78
  We're then "chunking" the plaintext content into different pieces, but that's mostly an Algolia implementation detail. We can just continue to do that just as before.

Doing option 2 is not much work at all, only a few hours.

Also, keep in mind that fulltext search is surely nice-to-have, but is not the most important search feature since I'd wager most content is found by title + tags alone. So, we don't have to overthink this problem.

**Comment by mlbrgl** [comment]
Starting with option 2 was my intuition too. We can add more structured records later on.
