### ISSUE TITLE
Resizing the window breaks hidden charts in the Key Insights block

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#1929]
## Description

A somewhat rare interaction that can crash individual Graphers until the page is reloaded.

1. Navigate to a key insight that has a Grapher
2. Navigate to a different key insight
3. Resize the page
4. Navigate back to the key insight with the Grapher
5. `Error: i[t] is undefined`

Presumably something to do with state being lost during the rerender

https://user-images.githubusercontent.com/11844404/219011076-a531b342-3f21-47ef-b73a-5f7fa58469f9.mov

**Comment by marcelgerber** [comment]
I think what's contributing to this is the Grapher resize handler: https://github.com/owid/owid-grapher/blob/d9b9dfceba8a7479026faac01ebbbdc51917300b/packages/%40ourworldindata/grapher/src/core/Grapher.tsx#L1626-L1643

It fires for every grapher that has already been mounted, including ones which are currently hidden. Since the bounds are calculated from the size of the container, the graphers that are not currently visible get a bounds object of `{x: 0, y: 0, width: 0, height: 0}`.
I assume this is then breaking things in the faceting layout logic for `FacetChart`s, and in fact other chart types break in other ways (see https://ourworldindata.org/democracy for example).

So, in reality, this resize handler should probably return early when the chart is not currently visible, and then we need to also ensure in some way that the grapher bounds are _eventually_ updated.
