### ISSUE TITLE
Issue during development

### ISSUE THREAD

**Issue by YannyTwoo** [owid/owid-grapher#1930]
## Description
Getting an error cause of "isKeyChart" and not being able to work with the admin panel locally

<img width="966" alt="Screenshot 2023-02-15 at 4 37 20 PM" src="https://user-images.githubusercontent.com/79789927/219016267-14a33b3e-7b56-42a3-9f56-b0c7c5707a98.png">

## Steps to reproduce

1. git pull
2. run the setup
3. go to localhost:3030/admin and this pops up

## Environment

For desktop, provide:

-   OS: OS Ventura
-   Chrome/Safari/Firefox

## Additional context

This wasn't an issue until today

**Comment by ikesau** [comment]
Hey @YannyTwoo 🙂 

We recently added a migration that changed the name of this property. The error you're getting is because you haven't run the migration on your local database, which can be done by running `yarn runDbMigrations` while your database is running.

One debugging trick I often use is to use GitHub's search to query the codebase for the names of values mentioned in the error message.

e.g. https://github.com/owid/owid-grapher/search?q=isKeyChart

Oftentimes this won't find anything, but in this case it may have helped you find the pull request or issue which would have explained the change.

Thanks!

**Comment by YannyTwoo** [comment]
Oh ok.
Thank you so much for explaining out simple queries with so much patience😅
