### ISSUE TITLE
Faceting: Uniform y axis sometimes doesn't work well with "Missing data" facets

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#2110]
## Description

The "uniform y axis" option should show a y domain that fits all facets well, and is dictated by the highest y values in the facets.
However, at least for the below StackedArea chart, it doesn't do that, and instead chooses a shared domain that essentially makes all data invisible.

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/electricity-prod-source-stacked?facet=metric&country=ASM~ABW

## Screenshots

![image](https://user-images.githubusercontent.com/2641501/232511646-4551535c-0783-406f-8856-91deacb90398.png)

## Additional context

The related faceting code is here:
https://github.com/owid/owid-grapher/blob/1fee189d7932ba6ca8626de0ac8f0f2b51438d37/packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx#L378-L386

The related AbstractStackedChart line is this one here:
https://github.com/owid/owid-grapher/blob/1fee189d7932ba6ca8626de0ac8f0f2b51438d37/packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx#L217

Essentially, what's happening is that the three facets with data are contributing a domain of `[0, 0.x]`, whereas the other facets are communicating a domain of `[0, 100]`.
We probably shouldn't set a domain for charts that fail (and hence don't have a axis).

This issue might very well also affect other chart types, didn't check.

**Comment by sophiamersmann** [comment]
I just looked into this and realised that allowing the domain to be undefined or null is a bit painful because then we would need to handle the undefined/null case wherever the domain is used. How about we simply make the domain an empty range in case of missing data, i.e. change this line

https://github.com/owid/owid-grapher/blob/1fee189d7932ba6ca8626de0ac8f0f2b51438d37/packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx#L217

to 

```ts
else axis.updateDomainPreservingUserSettings([0, max(yValues) ?? 0])
```

instead? I can't think of any downsides from the top of my head but wanted to check in with you before opening a PR. What do you think, @marcelgerber?

**Comment by marcelgerber** [comment]
Yeah, that'd work well too.
I initially thought that this could then cause problems for LineCharts because they are not necessarily all starting at `y=0`, but that's not a problem because they use a different fallback domain (which is to say that they, [in fact](https://ourworldindata.org/grapher/life-expectancy?time=earliest..1930&facet=entity&country=WLF~FRA~SWE), use `[NaN, NaN]`, probably more of an accident than a choice).

So yeah, using `[0, 0]` for stacked charts is a good choice, since they are always 0-based. Go for it!
