### ISSUE TITLE
Sunset data import via the Grapher admin

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2132]
## What

Check who's still using the grapher admin to import data, migrate them to fast track, and disable the old interface.

## Why

The ability to add data via the admin makes dev and staging environments much more complex to manage, and also causes us to need to do permanent backporting to the ETL.

**Comment by Marigold** [comment]
I spoke to several people who have modified datasets recently and there seems to be a need for editing data of old datasets. For instance [this dataset](https://owid.cloud/admin/datasets/5781) had an error in years column and had to be updated. Downloading & uploading corrected dataset via **CSV Import was just much faster than migrating it to fast-track format**.

For these cases we need migration tool (I was about to say "backporting tool", but that term is too overloaded) that would be able instantly replicate dataset in ETL.

### Migration tool proposal

CLI tool that grabs all data & metadata from MySQL and creates:
1. grapher step in the `owid` namespace with the same name
2. metadata YAML with all metadata in the grapher step
3. snapshot from data
4. ingest script for uploading snapshot from given path

Running grapher step should upsert against the existing dataset (and not change anything). If we want to make changes to data we'd download the data, update it locally and reupload with ingest script.

This is similar to fast-track, but **avoids Google sheets**. Coding this should be trivial as we've already done the same in walkthrough & fast-track. An alternative would be creating google sheet with all the metadata, but that sounds like a lot more work.

This could be also useful as an alternative to backported datasets.

One risk is keeping it in `owid` namespace, because dataset and variable metadata of these datasets is **editable**. If someone edits them, it might get later overwritten by ETL. That means all changes to metadata would have to be done in metadata YAML.

**Comment by Marigold** [comment]
## Datasets updated through CSV Import

* [Excess Mortality Estimates – The Economist (2023)](https://owid.cloud/admin/datasets/5429) - there's [an issue](https://github.com/owid/owid-issues/issues/921) for migrating it to ETL
* [AI Input Trends Data – Sevilla et al. (2023)](https://owid.cloud/admin/datasets/5515)
* [Researcher Affiliation Notable AI Systems Data – Sevilla et al. (2023)](https://owid.cloud/admin/datasets/5661) - both datasets come from Google Spreadsheets, they look like a good candidates for fast-track migration

**Comment by marcelgerber** [comment]
@Marigold I think this is completely done by #2405 and can be closed, right?

**Comment by danyx23** [comment]
Jep! :)
