### ISSUE TITLE
Multiple country selection fails for a stacked area chart

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2150]
## Overview

In some cases, stacked area charts no longer allow country selection. When multiple countries are selected, the faceting review only reflects a single country.

## Example

In the following chart, when you select two entities, only one is shown, but faceted.

<img width="1216" alt="Screenshot 2023-04-26 at 13 04 13" src="https://user-images.githubusercontent.com/36012/234569272-810f09ef-4d6c-4f48-9e09-2cbf4d494e08.png">

https://ourworldindata.org/grapher/child-deaths-by-life-stage?country=OWID_WRL~AFG

**Comment by marcelgerber** [comment]
Not entirely correct; the other countries are also shown, they are just so tiny in your screenshot above that Afghanistan is not visible:
![image](https://user-images.githubusercontent.com/2641501/234593032-46a4d577-af76-4a79-9f51-cd89a5d5a8eb.png)

What's jarring, though, is that it goes to per-metric faceting automatically in multi-entity mode.
Turns out, that's a data issue: https://github.com/owid/owid-grapher/pull/1977 is at play here, because we have multiple units set for the chart:
![image](https://user-images.githubusercontent.com/2641501/234593546-5559adcd-5091-40ae-bff8-2a7628e2fce3.png)

I'll fix it quickly for this chart, but we should of course watch out for more such cases.

**Comment by sophiamersmann** [comment]
At the very least, the choice of colours is suboptimal. I opened a new issue regarding this in #2155 and will close this one down.
