### ISSUE TITLE
Map tooltip reads "Click for change over time" but displays a bar chart on click

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2309]
## Description

This happens for collapsed line charts.

## Expected behaviour

~The tooltip should say "Click to select" (or similar).~ Reset the timeline when clicking on a country,

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/death-rates-from-eating-disorders
2. Hover over Australia
3. Note that it says "Click for change over time"
4. Click
5. Note that a bar chart is displayed

## Screenshots

<img width="1202" alt="Screenshot 2023-06-12 at 10 47 39" src="https://github.com/owid/owid-grapher/assets/12461810/2dd0b437-030b-4a45-8b08-196ffd29abfb">

## Additional context

Would also be fixed by changing the chart type to discrete bar (but that might not be desired)

**Comment by larsyencken** [comment]
Interesting. This case only happens when the timeline is collapsed, and even then, only sometimes.

I'm inclined to say that clicking a country on the map should reset the timeline selection to full width, which case the label could be the same.

The alternative is fixing the label but letting you click and get just a single bar for that time point, which doesn't make a lot of sense. (Bars are great when multiple entities are selected, but not good for any single entity.)

Any objections to modifying the time selection this way?

**Comment by sophiamersmann** [comment]
That makes sense! Thank you for investigating.
