### ISSUE TITLE
SVG embeds aren't loading webfonts correctly

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2343]
As noticed in https://github.com/owid/owid-issues/issues/901

If you don't have Playfair Display and Lato installed locally, the browser will fallback to its respective serif and sans-serif defaults, which makes it look like some poorly localized instruction manual.

![image](https://github.com/owid/owid-grapher/assets/11844404/c0487282-f425-45c7-868f-850caad01a10)

I think the issue is (at least) two-fold:
1. We're not embedding the webfonts into the SVGs
3. We're exporting the SVGs from Illustrator with suboptimal settings.

I've made a test repo to demonstrate how we could properly embed the webfonts in our SVG files as part of the baking process: https://github.com/ikesau/webfont-test

But even after adding the `<style>` rule to `population-projections-vs-estimates.svg` so that the fonts load correctly, the text is slightly misplaced. 

If we still want to try to use SVGs everywhere, we should work out what settings work best in the export from Illustrator.

It would also be a nice time to address https://github.com/owid/owid-grapher/issues/1910

In sum, I think the work for this entails:
1. **Find the Illustrator settings that work best across all browsers. If we can't, abort this issue and just use WebP/PNG everywhere**
2. **Self-host our webfonts**
3. **Add a step to the image baker that inserts the <style> rule that loads these webfonts into SVG graphers and also bespoke visualisations**

**Comment by mathisonian** [comment]
(copying this from slack so we have all the discussion here on GitHub)

I'm wondering if instead of trying to fix SVGs, we should live with PNGs for a little bit and implement ai2html support going forward. That way we don't have to deal with trying to embed the fonts and the text just becomes normal html and inherits styles from the site. The downside is it will take a bit of work to support, another upside is that we can have different mobile/desktop versions.

I also agree it would be nice to host the fonts ourselves.

**Comment by ikesau** [comment]
Yeah it's good to keep that in mind given it's a long term goal of ours. Seems like a much bigger project than either of the other two options, though.

If we switch back to raster for article visualizations, we'll still want SVG exports of Graphers for the wiki folks, so it'll still need to be fixed.

(This whole time it looks like my browser's been falling back to Garamond and Helvetica.)

**Comment by marcelgerber** [comment]
Another option we have is to convert the text to outlines.

This is, [apparently, possible in Illustrator](https://graphicdesign.stackexchange.com/questions/27238/preserving-font-type-in-illustrator-svg-file), and should have a similar effect to how fonts are always available in pdfs.

**Comment by ikesau** [comment]
In the few tests I've run, converting text to paths increases the filesize to equivalent-or-greater-than WebP, and would also remove the machine-readable property. By that point, I think I'd prefer the simplicity of only having high quality bitmaps.

**Comment by samizdatco** [comment]
It turns out Illustrator can actually be coaxed into generating SVGs that will work. 

## Font setup
The first issue is making sure that the fonts you're using in the app are the TTFs we'll be pointing to from the stylesheet, **not** the copies provided by Adobe via auto-activation. Start by opening up the Creative Cloud app and choosing "Manage fonts" in the sidebar:
<img width="240" alt="image" src="https://github.com/owid/owid-grapher/assets/469523/958d283e-30bd-4d3b-8379-e3a8456328f9">

Make sure Lato and Playfair Display are both either listed as "Previously active" or are simply not present in the "Active fonts" list: 
<img width="1136" alt="image" src="https://github.com/owid/owid-grapher/assets/469523/18900025-d87d-4e85-948b-3d580d4bc82c">

Next, download TTF copies of both families [from Ike's repo](https://github.com/ikesau/webfont-test/tree/main/fonts) and open them in the Finder. Click the "Install Font" button on the dialog that appears for each:
<img width="928" alt="image" src="https://github.com/owid/owid-grapher/assets/469523/f347b876-27d4-4834-af20-e6a87058e575">

Relaunch Illustrator at this point and reopen your documents to make sure it's seeing the new copies of the fonts (just in case). You'll know it's still using the old one if you see a ◆ in font's name in the Character palette.

## Export setup
To generate an SVG you'll want to use the "Export for screens" menu item:
<img width="782" alt="image" src="https://github.com/owid/owid-grapher/assets/469523/9e1df39c-d990-43af-833b-68d701a462aa">

Choose SVG from the dropdown menu in the Formats pane:
<img width="937" alt="image" src="https://github.com/owid/owid-grapher/assets/469523/95036577-0138-4851-a4b9-8bd13113ad7d">

Click the gear icon to its right to open the Format Settings window (make sure you select SVG in the sidebar since it displays PNG settings by default). Choose these options then Save Settings:
<img width="735" alt="image" src="https://github.com/owid/owid-grapher/assets/469523/30955af3-f0b9-44a9-965b-8f867b7f7fa4">

You can now click the Export Artwork button in the Export for Screens dialog and it will create a new SVG file in the selected directory.

## SVG Post-processing

The SVG only has references to the font family names, not the outlines themselves. Unless the user has the right versions of these fonts installed, they'll see a garbled version of the text with strange line and character spacing. We can fix this by inserting a css import into the SVG file's `<style>` element and setting up the proper `@font-face` definitions within that file (presuming we can get CORS to cooperate):
<img width="730" alt="image" src="https://github.com/owid/owid-grapher/assets/469523/506cda6c-94e2-4b70-b920-783e3d584586">

**Comment by larsyencken** [comment]
Thanks @samizdatco for the Illustrator workflow.

@ikesau Shall we close this issue then, and simply point authors to this workflow if they're using Illustrator? Or is there something more we need to do here?

**Comment by ikesau** [comment]
This needs to stay open 🙂 

We still need to [self-host our webfonts](https://github.com/owid/owid-grapher/issues/1910) and embed them in these SVGs via some automation step that adds the `<style>` tag to each SVG we host.

**Comment by larsyencken** [comment]
Calling this closed for now. If there's more to do, we can open a new more specific issue.
