### ISSUE TITLE
Auto log-in to admin on dev and staging servers

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2493]
## Problem

Today we serve a login screen with dummy credentials on dev and staging. Although they're not hard to fill in, it's tedious to have to, and other team members who don't use staging as much can get confused.

## Proposal

We should automatically auth with dummy credentials if we're in dev or staging, or detect that environment and autofill those credentials to make it simpler for everyone.

**Comment by marcelgerber** [comment]
We could probably just fill these in as the default values into the login screen as a super simple solution, since we're only really showing the password-authentication screen in environments where admin@example.com is available (local dev, staging on foundation).

It's a super easy solution and still makes the login flow explicit, which can potentially help us in debugging issues there.

**Comment by danyx23** [comment]
I just need to tweek #2399 a little which would be a stop gap improvement so that people no longer stumble over this. Will try to merge it today

**Comment by larsyencken** [comment]
Thanks Daniel. I would be inclined to follow Marcel's suggestion to autofill rather than hint, since there's currently no live flow where we use actual credentials here. We can still have people click to login.

**Comment by danyx23** [comment]
Yeah true. Switched to defaultValue instead and will merge this now

**Comment by marcelgerber** [comment]
I think our current solution (#2399) is good enough for now, closing this.
