### ISSUE TITLE
Improve support for single-indicator scatterplots

### ISSUE THREAD

**Issue by samizdatco** [owid/owid-grapher#2500]
## Core problem

It's currently difficult to configure scatterplots that compare a single indicator at two time-points using the admin. One of the times is determined by the chart's time slider while the other has to be locked in place by setting a `dimensions[].targetYear` override. There is also an inconsistency problem among our [existing single-indicator scatterplots](https://owid.cloud/admin/test/embeds?ids=948,867,1148,1169,1274,1891,3163,3417,3761,3762,3771,3775,3776,3777,3794,3803,3804,3957,5532,6438,6499,6501,6502,6503,6504,6505,6506,6507,6515) where the earlier year is sometimes plotted on the x-axis and sometimes on the y-axis. 

## Proposed solution

Adding a 'single indicator comparison' flag to the scatterplot config that adds special-case behavior where the 'start' and 'end' times are set via the time-range slider. Even if the slider is not exposed to users, this still makes for a better authoring experience (and allows us to ensure that the earlier date is on the x-axis and thus increases are above the diagonal). This consistent ordering would allow us to add labeling to the diagonal indicating the 'increase' and 'decrease' regions of the chart.

There is also the option of displaying the time slider in the published chart, allowing users to select their own comparison dates.

**Comment by larsyencken** [comment]
From discussion with Sophia, the current implementation of this has a ton of baggage, in particular it has performance issues because of the ordering of the table transforms. When you try changing the target year in the admin, it's very sluggish. That means to make this better, we'd have to invest in the other issues first. 

Since we don't have a ton of single indicator scatters, inclined to call this one "won't do" at this stage, unless the other issues get fixed.
