### ISSUE TITLE
Enable default entity selection for explorers on the chart level

### ISSUE THREAD

**Issue by bastianherre** [owid/owid-grapher#2513]
## Core problem
In explorers, `selection` sets default entities to display across all charts in an explorer. But sometimes, we would like to deviate from this default for a few charts to create additional chart types.

Additionally, sometimes the entities differ across data sources, so we could not set it at the explorer level even if we wanted to.

For example, in the draft [Conflict Data Explorer](https://owid.cloud/admin/explorers/history-of-war), the explorer's default entity is `World`. But we would like to switch to selecting all world regions for a few charts to create stacked bar charts.

## Proposed solution
Ideally, we would be able to set the selection at the chart level. 

## Alternatives
Alternatively, we have to create these charts individually and add them via chart ID in an otherwise indicator-based explorer.

**Comment by sophiamersmann** [comment]
It's not clear to me how to best implement this. I can see two options, one more extreme than the other:

Option 1: Default entity selections are only taken into account on page load. Once the user starts interacting with the explorer, the currently selected entities are always persisted.

Option 2 (more extreme): When a user interacts with an explorer and hasn't actively changed the selected entities, then the default selections are used.

For example, let's say Chart A has `World` selected by default and Chart B has `Spain` selected by default
- In case of Option 1: The user is on Chart A with `World` selected -> The user clicks on Chart B -> Chart B has `World` selected (since the entity selection is always persisted on interactions)
- In case of Option 2: The user is on Chart A with `World` selected -> The user clicks on Chart B -> Chart B has `Spain` selected (since that is the default selection for Chart B and the user has not actively changed the entities)
  - However, if the user adds/removes entities, the entity selection is persisted: The user is on Chart A with `World` selected -> The user adds `Austria` -> The user clicks on Chart B -> Chart B has `World` and `Austria` selected (the entity selection is persisted since it's coming from the user)

Option 2 might be confusing to users. I'm wondering what you had in mind and if Option 1 is good enough for your use case.



---


For example, let's say Chart A has `World` selected by default and Chart B has `Spain` selected by default.
- In case of Option 1: The user is on Chart A with `World` selected -> The user clicks on Chart B -> Chart B has `World` selected (since the entity selection is always preserved)
- In case of Option 2: The user is on Chart A with `World` selected -> The user clicks on Chart B -> Chart B has `Spain` selected (since that is the default selection for Chart B and the user has not actively changed the entities)
  - However: The user is on Chart A with `World` selected -> The user adds `Austria` -> The user clicks on Chart B -> Chart B has both `World` and `Austria` selected (the entity selection is preserved since it comes from the user)

Option 2 might confuse users. I'm curious about what you had in mind and whether Option 1 suffices for your use case.

**Comment by sophiamersmann** [comment]
I accidentally hit the Close button...

**Comment by marcelgerber** [comment]
The problem I see with option 1 is that the case that a user comes to "just the right" view of an explorer is rare (it is the case with embeds, but there we can set the entities to show anyway).

But yeah, I can totally see how the concept of an explorer falls down a bit when changing the shown entities without user interaction, since it then feels less like one cohesive exploration tool and perhaps more like a "carousel of charts".

For reference, we've had problems in the past where available entities for different views are vastly different or even disjunct; for example the [climate change explorer](https://ourworldindata.org/explorers/climate-change?facet=none&country=OWID_WRL~ATA~Gulkana+Glacier~Lemon+Creek+Glacier~OWID_NAM~South+Cascade+Glacier~Wolverine+Glacier~Hawaii&Metric=Snow+cover&Long-run+series=false) is such a case (some views only have "North America", others only have "World", etc.).

I've put this topic on the data viz agenda for Wednesday.

**Comment by danyx23** [comment]
Maybe it is enough to reset to the default selection only if the de facto selection would be empty after switching the view? I.e. if you have two indicators that don't have any overlap in their selection it would reset to the default whenever you switch. 

With this approach, if dataset A has `Austria` and dataset B has `Austria-Hungary` but both have `Spain` and `France` and `France` is the default, then the selected entities would work like this:

```mermaid
flowchart LR
    A1[Dataset A: Austria] -->|Switch to B| B1[Dataset B: France]
    A2[Dataset A: Spain] -->|Switch to B| B2[Dataset B: Spain]
```

**Comment by bastianherre** [comment]
Lucas adds to this conversation in [this](https://github.com/owid/owid-grapher/issues/2586) related issue.

**Comment by larsyencken** [comment]
I think this is the same as #2566, let's continue the discussion there.
