### ISSUE TITLE
Bug: chart showing entities with no data.

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#2541]
## Description

Some charts show entities in the selection menu that do not have data.

## Expected behaviour

Data 
## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/hivaids-funding-by-source
2. Click on '+ Add country or region'
3. Choose a country with missing data (there are several). Take Spain or Liechtenstein for instance
4. "No matching data" message will be displayed

## Screenshots

<img width="984" alt="image" src="https://github.com/owid/owid-grapher/assets/18101289/e857d8e6-239e-4e8a-aadf-3e5e1411a68c">

<img width="1104" alt="image" src="https://github.com/owid/owid-grapher/assets/18101289/a1647834-6c9e-4c6c-bf25-927c62ecd4e6">

## Environment

For desktop, provide:

-   OS: MacOS 13.5
-   Browser:  Brave v1.52.126 (Chromium: 114.0.5735.133)

**Comment by sophiamersmann** [comment]
Hey! I see data for Spain now; I'm assuming you've set the Missing Data Strategy to "Show entities with missing data" in the meantime. By default, StackedArea charts hide entities with missing data to prevent showing misleading charts. It's true, though, that if the Missing Data Strategy is set to "Hide entities with missing data" (= "Automatic" for stacked area charts), Grapher has a bug where entities are selectable that have no plottable data. We're tracking this bug [here](https://github.com/owid/owid-grapher/issues/1341). It is tagged as important, but unfortunately, it's tricky to solve since it likely would need some architectural changes. Not sure when we'll be able to address this, but I'll bring it up in this week's data viz meeting; maybe we find a way :)

I'm closing this issue in favour of https://github.com/owid/owid-grapher/issues/1341. Please reopen if I misunderstood or if you're describing something else.

**Comment by lucasrodes** [comment]
thanks, @sophiamersmann !
