### ISSUE TITLE
Data pages: source tab hotfixes

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#2756]
* [x] `Origin.description` doesn't render line breaks in `Sources and processing` tab
* [x] Combined `Data published by` from [sources and origins](https://github.com/owid/owid-grapher/blob/master/packages/%40ourworldindata/grapher/src/sourcesTab/SourcesTab.tsx#L101) might be non-unique - Duplicate mention below as "Names are repeated in `This data is based on the following sources`, because I used two files from the same author. Should I set this differently?"
* [x] In the sources tab, the "link" field shows only links for the first origin, e.g. [this chart](https://owid.cloud/admin/charts/5421/edit) (that shows only the link for population). Also, the "retrieved" field is also the one for population; in this case, there's an ambiguity, but maybe we should pick the latest date of all origins.
* [x] The text from `description_key` is not being surfaced in the sources tab.

**Comment by lucasrodes** [comment]
- [ ] The indicator name in the sources tab follows the prioritisation scheme: `presentation.title_public > indicator.title`. I think it should be `presentation.grapher_config.title > display.name > indicator.title` . We should be able to overwrite the indicator name shown in the sources tab. Using `presentation.title_public` is not ideal, because this field might not contain dimensions, as these might be in `presentation.title_variant`, and the name in the sources tab should contain the dimensions.
- [ ] The indicator name in the data page title follows the prioritisation scheme: `presentation.title_public > presentation.grapher_config.title > indicator.title`. Pablo proposes using `presentation.title_public > presentation.grapher_config.title > display.name > indicator.title` instead.

**Comment by lucasrodes** [comment]
I think that for the title of the data page, we could go with: `presentation.title_public > display.name > indicator.title `. I don't think `presentation.grapher_config.title` is relevant here, as it feels chart-centric.
