### ISSUE TITLE
Don't animate a scatter plot as a time scatter

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2855]
Animating a time scatter can be overwhelming. It would be better if we animated the dots only.

Example of a scatter plot animation:

https://github.com/owid/owid-grapher/assets/12461810/557c3d11-9b5e-4394-ae7b-4f67f7afe2c9

More videos in this Slack thread: https://owid.slack.com/archives/C0149NKLZAM/p1697710951929099

**Comment by toni-sharpe** [comment]
I thought I'd share this as I looked at what it would be like slower, it seemed to me that otiginal example is too fast. Here it is anyway. I still think there's problems, but I thought I'd share anyway.

## Original (~1s)

https://github.com/owid/owid-grapher/assets/10499070/b52a4855-3594-4c93-a54f-9d45421d3ecc

## Slowed 10X

- I had to cut it at around 7s as it needed to be less than 10mb.
- It would benefit from single year jumps not five year jumps too.
- Even monthly jumps (data permitting)

That being said, it's a dense graph, and even at the slower speed it could probably do with fewer points. I don't think it's the right graph to animate, but possibly there's no issue animating this graph-type.

https://github.com/owid/owid-grapher/assets/10499070/19a24f71-606e-4575-ad9c-d1f151ff7f62

I've been trying to get the app running locally so I can do something instead of just talking, but stuck right now - it seems mysql never completes, although it says it is found and has loaded, etc. As in, I can't see anything wrong, the dots just don't end and URLs don't work.

I need another look at that one, as I know there's some issues raised with answers, but I reverted to my map-based stuff for a while as I was making good progress there.

**Comment by sophiamersmann** [comment]
Implemented in #4038
