### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS on /entries-by-year

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#2936]
Go to https://ourworldindata.org/entries-by-year/

**Comment by marcelgerber** [comment]
Ah, this is happening because this is our only page (I checked) that relies on a `index.html` being present.

This line removes the trailing slash, and then Cloudflare itself adds it back because it needs it to resolve the file.
https://github.com/owid/owid-grapher/blob/ca12d6e5a1bd1a06eb46527cbbe9c587ad3f31d8/baker/redirects.ts#L24-L25

I think adding a line like `/entries-by-year /entries-by-year/index.html 200` should work. @danyx23 could you try that maybe?
