### ISSUE TITLE
Grapher's modal backdrop doesn't cover the whole frame when embedded in an article and viewed on a small screen

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#3010]
## Description

- On small screens, Grapher is optimised for horizontal space
    - Grapher bleeds onto the edges horizontally and the top and bottom borders stretch across the entire page (see screenshot)
- When a modal is open, the backdrop should also stretch across the entire page, but it doesn't

## Expected behaviour

- Backdrop always covers the entire frame

## Steps to reproduce

1. Go to on a mobile phone: https://ourworldindata.org/how-are-incomes-adjusted-for-inflation
2. Scroll to the "Consumer price index" chart
3. Open a modal
4. See that the backdrop doesn't cover the entire Grapher frame

## Screenshots

<img width="407" alt="Screenshot 2023-12-11 at 11 12 39" src="https://github.com/owid/owid-grapher/assets/12461810/26557564-868e-4bbf-936a-c1c9f90cd65e">
<img width="407" alt="Screenshot 2023-12-11 at 11 12 45" src="https://github.com/owid/owid-grapher/assets/12461810/bd9e1a55-daf9-4480-ad0a-0708590bb43a">

**Comment by danyx23** [comment]
Grapher should probably flag that it is in "dimmed background" mode and then the page should react to it - otherwise it would be a major restructuring of the layout logic of Grapher. Toggling a css class on the grapher component (?) is probably the easiest way of doing this.

Maybe this should be part of the #3070 project?
