### ISSUE TITLE
owid.entry.ts loaded twice

### ISSUE THREAD

**Issue by breck7** [owid/owid-grapher#324]
Repro:
1. Open dev tools and watch XHR network traffic.
2. Visit a page like: https://ourworldindata.org/grapher/life-expectancy?tab=map&year=1918&time=1830..2019&country=FIN+NOR+ESP+SWE+CHE+USA

Expected: One Amplitude OWID_PAGE_LOAD post.

Actual: Two Amplitude OWID_PAGE_LOAD posts.

So far in my investigating it seems the code in 'owid.entry.ts' is run twice on certain pages.

In addition to the `Analytics.logEvent("OWID_PAGE_LOAD")` line firing twice, all code in that file seems to run twice, including the code that adds the `data-track-click` functionality, so there are two independent callbacks on all clicks.

This does not happen on all pages, for example the https://ourworldindata.org/spanish-flu-largest-influenza-pandemic-in-history page loads fine.

It is easy to reproduce locally by simple adding a line like `console.log("hello world")` to `owid.entry.ts` and visiting a page like `http://localhost:3099/grapher/natural-disasters-by-type`.

**Comment by MarcelGerber** [comment]
I looked into this, this happens because `owid.js` is referenced from multiple page elements, e.g.:
https://github.com/owid/owid-grapher/blob/dd2f4f21db22e1b74e5262f52b807950ab63b0fb/site/server/views/ChartPage.tsx#L114
https://github.com/owid/owid-grapher/blob/919e002a978905586d1071e911e5cdbc312cd60c/site/server/views/SiteFooter.tsx#L252

Since `SiteFooter` is part of just about every page, I think it would be enough if just it references `owid.js`.
The same probably goes for `common.js`, even though I don't know if loading it multiple times has any negative impact.

**Comment by breck7** [comment]
That looks like the problem! Nice work @MarcelGerber !

**Comment by danielgavrilov** [comment]
Awesome, thanks for looking into this @MarcelGerber!
