### ISSUE TITLE
Remove the entries-by-year indices

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#3334]
We should remove the entries-by-year pages. They're incorrect and not linked to anywhere. The site nav should be the primary way people discover our topics.

e.g.

https://ourworldindata.org/entries-by-year

https://ourworldindata.org/entries-by-year/2023

Make sure redirects are added for all these pages once the work is completed.

**Comment by danyx23** [comment]
This is almost soonish-and-small but needs to be checked with @JoeHasell to see if the plan is to send only modular and linear topic pages or also articles.

**Comment by ikesau** [comment]
I think the way this issue is framed is misleading 🙂 

As far as I can tell, Google doesn't care about having an "entries-by-year" file to index. I think that's more for our readers - an alternative to the site header navigation as a method to overview all our content.

For Google Scholar, the main thing is having the [correct meta tags on our articles](https://scholar.google.ca/intl/en/scholar/inclusion.html#indexing) as illustrated by the fact that [gdocs articles are being included in google scholar already.
](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=our+world+in+data)

And imo, given the page is for our readers and not google, the entries by year file should definitely include modular and linear topic pages (including the [modular topic pages from wordpress](https://datasette-public.owid.io/owid?sql=SELECT%0D%0A++%22https%3A%2F%2Fourworldindata.org%2F%22%7C%7Cposts.slug+as+url%0D%0AFROM%0D%0A++posts%0D%0AWHERE%0D%0A++posts.content+LIKE+%27%25topic-page%25%27%0D%0A++AND+NOT+EXISTS+%28%0D%0A++++SELECT+1%0D%0A++++FROM+posts_gdocs%0D%0A++++WHERE+posts_gdocs.slug+%3D+posts.slug%0D%0A++%29%3B))

Then separately, we should double check that the meta tags for all gdocs posts are correct.

**Comment by JoeHasell** [comment]
Apologies for not engaging with this before @danyx23, and thanks for picking it up @rakyi!

I can't really speak to the technical question of what we should be sending to Google Scholar without more context. 

But if it's helpful, I can give a bit of background on the end goal/question 'Do we want people to be citing articles individually?' – which is something Daniel and I have spoken about before.

There's a (possibly rather wishful) hope Max and I have been discussing for a while: whether we could find a way to aggregate citations onto our topic pages. We have in mind a metaphor of an 'edited volume' – where the topic page is the book, and the charts and data pages are the chapters. The citation in an article would be something like '[Article title], in [topic]' and everytime people use that citation, the idea is that it would count towards the topic page citation count.

One motivation for this idea is that topics feel like the most fixed unit of our work. We might radically restructure or unpublish individual articles or data pages, but this is less likely/common for topics. It's a poor reflection of the impact of our work if citations are spread thinly across all these minor individual content pieces and versions. A better mental modal is that people are each time citing our 'volume' on e.g. Poverty, and that, as our content for a topic evolves, we are periodically releasing a new 'edition'.

(The 'editions' part is important for another reason. We also have the opposite problem where we are asking people to cite our latest Democracy work – which includes data up to 2022  – as having the publication year of 2013, because that's when we first published the topic page). 

**But!** This is all still a pretty vague idea at this point. The conversation has stalled a bit and there remains lots to think through – including the basic question of how much we can actually influence how people cite our work and how that then appears in Google Scholar.

So, overall, I'd be loathed for this currently loose thinking to block you. Hopefully this gives you more context you need to make a good decision – reach out if you think there's more I can help with.

**Comment by ikesau** [comment]
I've scoped this ticket down to the entries by year issue.

We can talk about google scholar citation stuff in the [owid-issues thread](https://github.com/owid/owid-issues/issues/1277).
