### ISSUE TITLE
LineChart/StackedArea: Improve labelling when space is tight

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#3351]
## Description

- When space is tight, the labelling algorithm used in line charts and stacked area charts doesn't do a good job
- This has been noted by Pablo A when trying to prepare a mobile static chart for data insights (see screenshots below)
- This is also the reason why we don't re-use the labelling algorithm for slope charts

## Expected behaviour

- Show as many labels as possible, even when space is tight

## Steps to reproduce

1. Go to https://owid.cloud/admin/charts/383/edit
2. Click on the 'Export' tab
3. Switch to the mobile version

## Screenshots

When space is tight:

<img width="563" alt="Screenshot 2024-03-15 at 12 02 04" src="https://github.com/owid/owid-grapher/assets/12461810/24f77321-8515-4823-840f-1deb590b1604">

If there is more space (here achieved by removing text elements):

<img width="563" alt="Screenshot 2024-03-15 at 12 02 29" src="https://github.com/owid/owid-grapher/assets/12461810/8e07a85f-83f6-4e53-85bb-b5e21ee7279a">

**Comment by danyx23** [comment]
Discussed this in issue triage - because this now comes up more in thumbnails and mobile chart exports we think it's important to fix this. 

To fix it, we should probably drop entities from the list of labelled entities if there is insufficient space until there is enough space. It's a bit unclear if we should drop entities by lowest value in the last year first or by area in the visible chart space.
