### ISSUE TITLE
Marimekko: No entity labels although there is space

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#3456]
## Description

- Marimekko charts sometimes don't displat any entity labels although there is space
- Seems to happen for chart views with few bars on screen

## Expected behaviour

- Show as many entity labels as possible

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/life-expectancy-marimekko?time=1877
2. Note that space for entity labels is reserved but none are displayed

## Screenshots

<img width="1273" alt="Screenshot 2024-04-08 at 09 33 15" src="https://github.com/owid/owid-grapher/assets/12461810/9ae6462f-dc1e-431d-b258-da7cd6ce25b0">

**Comment by toni-sharpe** [comment]
The problem is this: the logic that decides what `isPicked` for label candidacy uses the presense of a population as a filter, I think, 

Using the example in the issue, a [break-point in the Marimekko chart code here](https://github.com/owid/owid-grapher/blob/975c329a13f7a69129b02e987b048b04ca178e10/packages/%40ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx#L1242) and running the below in the inspector console yields two countries: Chad and Monaco.

```
const pickedChunks = chunks.filter(chunk => {
  // filter anything that has nothing at all or has nothing picked to display
  return chunk.length > 0 && chunk.filter(d => d.isPicked).length > 0
})

pickedChunks.forEach((chunk, i) => {
  // get the name of the picked entity that flagged this chunk
  // we should expect to place both these labels given the logic
  const pickedEntity = chunk.filter(d => d.isPicked)[0].item.entityName
  console.log(pickedEntity)
})
```

Tab to the chart, order by "Life expectancy" and neither report for that year.

![image](https://github.com/owid/owid-grapher/assets/10499070/6bcf20b4-10bc-45dd-ac96-a483c2542997)

What I would do: `20` is fixed. Works great with 200 countries, but I think needs to have a check:

```
labelCount = lifeExpectancyCount <= MAX_LABEL_COUNT
  ? lifeExpectancyCount
  : Math.min(pixelCount, MAX_LABEL_COUNT)
```

It's while since I did this style of production site based inspector debugging so I hoping I can actually edit and verify this in the browser, I'm sure I can, but that will not be today. However there's probably ten ways to fix this and the coding style here is very different to mine, I'd probably look to get rid of all null lifeExpectancy property entities, then check and return early for performance, as a lot of that `picked` code wouldn't be needed, but I don't know where I'd do that.

**Comment by toni-sharpe** [comment]
PR to fix: https://github.com/owid/owid-grapher/pull/3581
