### ISSUE TITLE
Knex migration slowed down content bakes

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#3462]
## Description

Migration to knex slowed down content bakes from ~7min to ~15min. The difference can be seen on these two builds - [before](https://buildkite.com/our-world-in-data/owid-deploy-content-master/builds/3208#018e7b02-ff54-4dbd-8dc3-cf8b550cd659) and [after](https://buildkite.com/our-world-in-data/owid-deploy-content-master/builds/3214#018e7bb6-19e2-4ff3-9515-a1e2a698d33f) (be aware that time bars on the right in buildkite correspond to the step on the next line!). Here's a breakdown:

1. `bakeAllChangedGrapherPagesVariablesPngSvgAndDeleteRemovedGraphers` - 5 min
2. `baked google doc posts` - 1 min
3. `baked special pages` - 1 min

## Expected behaviour

Such a large slowdown doesn't look like it is just knex overhead. Perhaps the schema has changed and we're missing indexes somewhere?

**Comment by marcelgerber** [comment]
Just a (somewhat informed) hunch:
I don't think it's any changes in indexes used, because there shouldn't be any.

I think, however, that the slowdown is (partly) in the gdocs handling in datapage baking code.
`DatapageHelpers#getDatapageGdoc` now calls `getGdocBaseObjectById` rather than `GdocPost.findOneBy`:
https://github.com/owid/owid-grapher/blob/abbc4e55712967b629eb0192cb31774a63f26973/baker/DatapageHelpers.ts#L104-L105

That method then calls `parsePostsGdocsRow` to enrich the entire Gdoc - which I guess we didn't do eagerly before (not sure)?
Or maybe there was a caching layer in place somewhere before, either implicit or explicit, that we now no longer have?

**Comment by ikesau** [comment]
[I did some benchmarking](https://observablehq.com/@ikesau/owid-bake-analysis) by baking 1000 charts with various things commented out.

The datapage code, while slow, is actually _faster_ than the Grapher path - `getPostEnrichedBySlug`, `getPostRelatedCharts`, and `getRelatedArticles` are all adding significant overhead and should be optimized.

I didn't find what was causing the datapage slowdown because I wasted a bunch of time with a flamegraph library, but DB access is what I'd check out first.

**Comment by marcelgerber** [comment]
So, @danyx23 and I looked into this for a bit.

This is actually happening because of: https://github.com/owid/owid-grapher/blob/d65c4ca6c37d80f6c5878eeaadd12b5f75779c7a/baker/GrapherBaker.tsx#L526-L527
In my testing, it turned out that with multiple transactions, the chart baking `yarn runLocalBake --steps charts` runs twice as fast.

Also, I sanity-checked that, when run with a single transaction, this is not using a connection pool but rather just a single connection.
You can try that yourself by running
```ts
console.log(
    await db.knexRawFirst(knex, "SELECT CONNECTION_ID() as connectionId")
)
```
-- for example, at the top of `bakeSingleGrapherChart`.

I think that using multiple transactions for baking is the way to go here.

**Comment by marcelgerber** [comment]
I think there's no way around this.
[According to this](https://stackoverflow.com/a/8377633), mysql cannot share transactions across multiple connections, which makes sense I guess.

I'm gonna assign this issue to @danyx23, just so we don't forget about it.

**Comment by danyx23** [comment]
@Marigold with the recent work from @ikesau and @marcelgerber we made some progress in bake times. Is this ok for now? If not please open a new issue and tell us which area we should focus on. Thanks!

**Comment by danyx23** [comment]
#3514 might also be related

**Comment by Marigold** [comment]
Marcel's fix helped. It's as smooth as before!
