### ISSUE TITLE
Minify SVGs?

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#366]
On every page, before the interactive charts are loaded, we first load the SVGs for the charts. 

(Try search for "svg" on page load on any entry, e.g. https://ourworldindata.org/coronavirus-data – the total is 724KB gzipped)

We could _probably_ minify our SVGs significantly without losing any detail. I've looked at [SVGO](https://github.com/svg/svgo/blob/master/README.md) for this, though there may be other options.

**Comment by MarcelGerber** [comment]
A quick look at [SVGOMG](https://jakearchibald.github.io/svgomg/), a frontend to SVGO, shows that we can save 45% in gzipped size for https://ourworldindata.org/exports/total-confirmed-cases-of-covid-19-per-million-people_v24_850x600.svg. (51.45k → 28.72k)

I disabled the setting "Collapse useless groups" because it messes up the OWID logo in the upper right, otherwise I went with the defaults.

There's a debate to be had about the precision we can use, with precision 0 (meaning no floating-point coordinates at all) still looking quite good and bringing the gzipped size down to 26% of the original. Since the svg is only a preview of the chart, we could maybe even go with that option?

**Comment by MarcelGerber** [comment]
Btw, the same goes for `png` graphics. While we show previews of lower resolution, https://ourworldindata.org/uploads/2020/03/COVID-CFR-by-age-768x595.png still weighs in with 250KB.

Using [imagemin](https://www.npmjs.com/package/imagemin), we can get that graphic down to 156KB and using [imagemin-pngquant](https://www.npmjs.com/package/imagemin) down to just 105KB.
The coronavirus page weighs in with about 800KB of pngs, so that could also a good way to shave some size off.

**Comment by breck7** [comment]
Awesome @MarcelGerber !

The code LGTM.

A quick `cd owid-static/grapher/exports; du -hc *.svg` shows me that the current static SVGs sum to 264MB.

I will merge this now and report back the global effect. I'll also do a broader visual inspection before pushing.
