### ISSUE TITLE
Tooltip layout in chart looks slightly off

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#3817]
## Description
When hovering over the chart area, the tooltip presents unexpected spacing between rows. It looks as if the column width of the table is wrongly defined?

## Expected behaviour
Spacing between rows should be the standard

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/covid-variants-bar
2. Hover over chart area

## Screenshots

![image](https://github.com/user-attachments/assets/6ddb656c-de02-4166-ac40-79b2c3ba0719)

## Environment

For desktop, provide:

-   OS: MacOS
-   Browser: Arc

**Comment by marcelgerber** [comment]
Probably a quick CSS fix to prevent the grid lines from breaking.

But it's also not much of an issue, since all information is still mostly readable in the tooltip, just in a not-nice way.

**Comment by toni-sharpe** [comment]
<img width="848" alt="image" src="https://github.com/user-attachments/assets/9106429c-c58a-4f6d-ad16-4227296bcfaf">

I got my head right into this last night: I looked at the CSS, yes, the things can be aligned, however, the date seems odd, effecting things like it is, appearing even though the slider extends beyond it and the country is still reporting. I might have fixed that, as in the image above, but I'm trying to be _much less verbose_, I say too much, unintended but too much for othe people, and I am fixing that as well.

The date thing is a bit more complex, it'll need more explanation. Available on request, in your own time. No rush here.

**Comment by toni-sharpe** [comment]
**Note: came back, no rush expected** - will share date detail this time as there's [another instance](https://github.com/owid/owid-grapher/issues/2714) - probably

<details>
  <summary>Date related problems with the tooltip</summary>

It's ones with extra data in:

France has &#x24D8; circle and date
Spain just a %

Wider bars visible on Chrome, my screen-shots FireFox.

This [TooltipTable](https://github.com/owid/owid-grapher/blob/master/packages/%40ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx#L817-L839) is the source, [specifically this time](https://github.com/owid/owid-grapher/blob/master/packages/%40ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx#L817-L839) which is refered to as [`endTime`](https://github.com/owid/owid-grapher/blob/master/packages/%40ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx#L774). End time sounds like "no more covid data" - in the code it looks like [scale end](https://github.com/owid/owid-grapher/blob/master/packages/%40ourworldindata/grapher/src/core/Grapher.tsx#L1104)? Could the countries have stopped reporting? 

The problem only occurs on countries who have this `endDate` set **and** it's **before** the current setting on the slider.

### Pic demonstrates, scale past end of some sort?

With Germany, end: 17-June, it's set to 3-June and fine.

<img width="160" alt="image" src="https://github.com/user-attachments/assets/faba83d4-2e9f-49c8-8a83-e3ee1254e540">&nbsp;&nbsp;<img width="160" alt="image" src="https://github.com/user-attachments/assets/475a74be-0471-4a0d-8a32-e50c05f57e30">&nbsp;&nbsp;<img width="350" alt="image" src="https://github.com/user-attachments/assets/e500ac19-d981-466b-b2a7-32cadd7ff7a7">

### Background info

Have the countries stopped reporting variants altogether? This [WHO report](https://www.who.int/activities/tracking-SARS-CoV-2-variants) stresses the need to keep going. Their latest map is 29-may-2024. Your data is last udated 26-jul, but this error only happens if the slider is after the `endDate` in the code (see screen-shots). That being said, digging inton GSAID (sourced by OWID) shows, even countries with bad dates are reporting day by day, strain by strain - this close monitoring isn't over.

### France, incorrect, Spain, no problem (no 1st July '24)

<img width="350" alt="image" src="https://github.com/user-attachments/assets/f6bf07f8-0b69-414e-a3fa-344fbbfa851e">&nbsp;&nbsp;<img width="350" alt="image" src="https://github.com/user-attachments/assets/07aa9a67-ce9a-4237-b956-b22bd8acb992">

</details>

**Comment by danyx23** [comment]
Hey @toni-sharpe, the date is important to keep as is - it tells users what date the shown value is from. We often use temporally sparse data and then show values with tolerance - if we do, we make sure in the tooltip to tell people from when a given time point is. You can see another example of how we do this in the map tab of the extreme poverty chart: https://ourworldindata.org/grapher/share-of-population-in-extreme-poverty

As such, it would be great to just fix the issue described above - that the tooltip sometimes spills over. It looks like adding a `min-width` of `8em` to `td.time-notice` in `packages/@ourworldindata/grapher/src/tooltip/Tooltip.scss` should do the trick but I haven't checked the other uses. If you like to investigate along these lines then please do!

**Comment by toni-sharpe** [comment]
@danyx23 OK, CSS until row, no problem,

The WHO want this heavily monitored, as do I, but that will become fuzzier as richer countries eliminate it. ie DE latest data is 17-jun, so as soon as we go to 01-jul there's "no data" which we imply with the last reported date. In a decade: lots of grey bars at least in the Global North.

Actually I'm starting on machine learning with Python like now pretty much, after that schema PR, so seen as there's two data tech folk right here: book recommendations would be most welcome.

This is what I'll call out in return [Wasteland - Oliver Franklin-Wallis](https://www.goodreads.com/book/show/121005922-wasteland) it's accessible, well researched, four year journey through the global waste industry historically and currently and it's fascinating, looking at your main menu here there's probably bits from every section that are connected. I shared the site which mentions BBC Radio 4 too, where I heard about it and home to lots of excellent, varied factual programmes. [Podcasts and ads for us outside the UK](https://www.bbc.co.uk/sounds/podcasts). 

<details>

<summary>Data nerdiness for the sake of it</summary>

@lucasrodes I can see is a data scientist and uses SQL, which is cool, I love SQL but also I've been using [Ramda.js](https://ramdajs.com/) for client-side data wrangling - [that's a trickier one](https://github.com/toni-sharpe/data-visualisation/blob/main/gui/src/util/UtilDynamicGrouping/UtilHistogramDynamicGrouping.js) which does the grouping [of these bars](https://data-visualisation.pages.dev/HistogramMaker). Here is some [example data](https://github.com/toni-sharpe/data-visualisation/blob/main/gui/src/util/UtilDynamicGrouping/UtilHistogramDynamicGrouping.example-data.js) where I've also been looking at how it's arranged to reflect what it is. Also, I'd like [a consistent structure](https://github.com/toni-sharpe/data-visualisation/blob/main/gui/src/util/UtilDynamicGrouping/UtilHistogramDynamicGrouping.example-data.js#L84-L87), three dimensions, grouped and exposing a meta-data pattern so I can bring the prediction and anti-bias things back from the actual medical graphs. 

</details>

Yes brevity.

**Comment by toni-sharpe** [comment]
@danyx23 I've found this, looks like I have implicitly commited to the fix, but it slipped under the radar a bit, a couople of real life issues have been a bother, but I'll comment now and take ownership of the fix, taking into account the new info.

Is there a deadline of any sort?

Also, I'm certainly curious what resources and books you're using for Machine Learning and Data Science, practical stuff, as I want to start on that to bolster the visual output. Also, that might help with employment. I'll not pester this question again, but the learning side needs feeding and I think the folks here are good to ask.

I'll start on this task during the rest of this week.

**Comment by toni-sharpe** [comment]
Nevermind deadlines: https://github.com/owid/owid-grapher/pull/3907

**Comment by sophiamersmann** [comment]
Is fixed
