### ISSUE TITLE
Colour selection is broken on scatterplots

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3819]
## Problem

When editing a scatterplot chart, it's not possible to edit the colours any more. Clicking on a colour brings up the colour picker, but clicking on new colour there does not change it.

## Expected behaviour

Clicking on the colour picker should let you change and update a colour in the scatterplot palette.

## Example

https://github.com/user-attachments/assets/8cfdebb3-a501-47e9-966d-9843a7b241c2

Reported by @veronikasamborska1994 and confirmed now.

**Comment by lucasrodes** [comment]
Heads up that this is interfering in several COVID scatter plots (unsure if others). Take [this one](https://admin.owid.io/admin/charts/4112/edit) as an example (shown below). For some unknown reason, the colours for the continents are not our defaults. I tried changing these, but couldn't because of this bug. But also I am unsure why the colours are not correctly assigned.


![COVID-19 Deaths vs Population](https://github.com/user-attachments/assets/26f8fda8-66e9-4504-a43f-631390ee32f7)

**Comment by larsyencken** [comment]
From a bisect, it's been broken > 6 months for scatterplots.

**Comment by marcelgerber** [comment]
We'll try to solve this in the coming weeks.

If we don't get around to solving this, then we can _probably_ work around it by manually editing the chart config.

**Comment by marcelgerber** [comment]
We just checked, and it is definitely possible to manually set properties like `colorScale.baseColorScheme` and `colorScale.customCategoryColors` manually in the chart config / database.
It's just the admin that won't let you change these.

**Comment by toni-sharpe** [comment]
Is [this issue](https://github.com/owid/owid-grapher/issues/3516) related?

 > region checkboxes in marimekko do not respond #3516

**Comment by danyx23** [comment]
@toni-sharpe yes I'm pretty sure these two issues are related. The bug seems to be in the admin as marcel said, but it's probably a tricky one to resolve. I quickly had a look if I could get a good hunch for the cause and give a hint but it wasn't clear to me where this problem comes from and why it works for some chart types but not others. I think fixing this bug needs a pretty deep understanding of the admin.

**Comment by toni-sharpe** [comment]
@danyx23 I got the same feeling. I had a good look, I like a challenge, it's very good for the brain, and I've got a couple here and there. 

Though as well that does have it's limits. I've no deep understanding of the admin and it's not simple either.

Good to pair on perhaps.

**Comment by danyx23** [comment]
We should probably only do up to three hours of bug investigation alone. If this takes longer then it's probably a better call to turn this into a mob debugging session.
