### ISSUE TITLE
Data: new continent indicator

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#4176]
## Context
I've updated our charts using our continent indicator (variableId `123`) to use an equivalent one which is in ETL (variable id `900801`). This indicator is based on our `regions.yml` definitions!

More context in https://github.com/owid/owid-issues/issues/1738.

In order to complete this migration, there some additional steps needed (continue reading...).

## Next steps

- [x] 1) Fix continent-coloring
- [x] 2) Stop showing citation in chart footer
- [ ] 3) Others

### 1) Colors
Currently, the colors used for each of the continents are not correct (in scatter plots, Marimekkos, etc.). Instead, we should use our defaults.

- Africa: #A2559C
- Asia: #00847E
- Europe: #4C6A9C
- North America: #E56E5A
- Oceania: #9A5129
- South America: #883039

Note: This also affects [explorer views](https://admin.owid.io/admin/explorers/ivs).

### 2) Citation
We should not add an explicit citation to the source of this indicator in our charts (this is the behaviour that we previously had with variable 123).

In addition, I would suggest that we _never_ show the source in chart footers for indicators in dataset `regions/2023-01-01/regions` (dataset id 6497). That's because we may want to color countries by other standards (e.g. WB, WHO, etc.).

The image below shows a chart with issues 1 and 2:

 ![Image](https://github.com/user-attachments/assets/f0b048cc-091e-4eca-b07a-cc94454f6b55)

### 3) Data points shown in gray
I've detected some scatter plots, where the data is shown in gray (regardless of the continent):

- [ ] https://ourworldindata.org/grapher/affected-by-disasters-vs-gdp
- [x] https://ourworldindata.org/grapher/literacy-rates-vs-average-years-of-schooling
- [ ] https://ourworldindata.org/grapher/death-rates-disaster-gdp
- [ ] https://ourworldindata.org/grapher/affected-by-disasters-vs-gdp

![Image](https://github.com/user-attachments/assets/d67dae5e-9a33-4426-a420-0ea31d1e629e)

### 4) Data is not found
I couldn't migrate the following charts. If I attempt to change variable 123 for the new indicator, I get a "No matching data" message and no data is shown. Therefore, I've decided not to migrate these.

- [ ] https://ourworldindata.org/grapher/distribution-democracy-index-polity
- [ ] https://ourworldindata.org/grapher/fertility-rate-vs-mean-years-of-schooling
- [ ] https://ourworldindata.org/grapher/distribution-democracy-index-popw-polity

![Image](https://github.com/user-attachments/assets/22632731-6560-454d-ae0d-77ecb22e6b94)
![Image](https://github.com/user-attachments/assets/5e7cb0c0-b90d-4a16-a7d0-871bd5a318b2)

**Comment by veronikasamborska1994** [comment]
@danyx23 I don't think it's likely Antarctica is the issue for 3 and 4 - I've checked and if you recreate the same chart from scratch it doesn't seem to be causing an issue - for example this [chart](https://admin.owid.io/admin/charts/8267/edit). I don't know what's exactly the issue but the problem seems to appear when you set the timeline max (see the screenshot where I've replicated it on the new [draft chart](https://admin.owid.io/admin/charts/8267/edit) that otherwise looks fine until you set the maximum on the timeline). I've briefly looked at the charts in 3 and 4 and seems like this might be the unifying feature across them


 ![Image](https://github.com/user-attachments/assets/0aa52fae-9358-4144-9c5b-283224bdc1ef)

**Comment by veronikasamborska1994** [comment]
@danyx23 we can fix all of these by setting the timeline max to default and simply using tolerance for some of these charts as I think the main reason why they were truncated was to show the year where more data was available - e.g.,  here is a fix for https://ourworldindata.org/grapher/distribution-democracy-index-polity chart ![Image](https://github.com/user-attachments/assets/a85fd4da-9483-400f-9232-2fd331ac6e9d)

**Comment by danyx23** [comment]
@veronikasamborska1994 ah thank you, that is very helpful! This means the error occurs because the new regions indicator has 2023 as the year and the old continents indciator had all the regions as 2015. Color should have an infinite tolerance implicitly but apparently there is a bug there somewhere.

**Comment by marcelgerber** [comment]
We're closing down this issue, and are tracking the remaining bug over in #4284.
