### ISSUE TITLE
Slope charts should have region legends like scatterplots

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#50]
This one should be reasonably straightforward.

We want to take the little legend from the scatterplot chart type, e.g. https://ourworldindata.org/grapher/urbanization-vs-gdp

And put it on the "slope chart" chart type, e.g. https://ourworldindata.org/grapher/access-to-a-financial-account-or-services

---

The relevant files to look at:

https://github.com/owid/owid-grapher/blob/master/js/charts/ScatterPlot.tsx
https://github.com/owid/owid-grapher/blob/master/js/charts/ScatterColorLegend.tsx
https://github.com/owid/owid-grapher/blob/master/js/charts/SlopeChart.tsx

**Comment by sherinkurian** [comment]
hi @mispy - I was hoping to contribute to this repo since I really enjoy OurWorldInData. 

to test the charts, this page seemed ideal http://localhost:8000/grapher/admin/testall?type=scatter. but the local urls are not working. 

1. 404 on embedCharts.js. it seems like this file is dynamically created and not sure how to generate that. 

<img width="1388" alt="screenshot 2018-05-26 19 09 22" src="https://user-images.githubusercontent.com/4923428/40581876-7c28b98e-6118-11e8-8a19-4fbbe5f87427.png">

2. There is a link to open the local chart in the html source ^  but when I try to access it from the browser, it throws a 404. 

```
<figure data-grapher-src="http://localhost:8000/grapher/top-MRTs-on-individual-income?tab=chart"></figure>
```

thank you!

**Comment by mispy** [comment]
Hi Sherin, thanks for taking a look! You are on the right track, cool that you found the testing url.

In order to test the "public" chart urls for the initial database charts you'll need to run a static build: `node dist/src/bakeCharts.js`. I've updated the README to reflect this.

**Comment by sherinkurian** [comment]
Hi Jaiden, thank you so much. Managed to get the embedCharts.js but got stuck on getting individual charts to load. I can take a look again to see what's up.

Meanwhile, I ended up using the node server instead at http://localhost:3030/admin/charts which worked without any changes. It seemed like the project is moving towards node? 

There is a PR for your review to set legend on slope charts :)
