### ISSUE TITLE
Importing CSV with dates instead of year

### ISSUE THREAD

**Issue by masaez** [owid/owid-grapher#606]
Guys, first let me start by congratulating a fantastic job with the data model, admin, and graphs. You have a fan here.

I am trying to create a chart using my own data, which consists of a series of float values for a given country. The time scale would be 'date', not year, but checking through the validation code, it looks like only years is accepted in /admin/import csv.

Any suggestion?

**Comment by masaez** [comment]
Trying to guess my own response here.. should I just enter the number of days from days Zero and then check the option "Treat year column as date"?

**Comment by masaez** [comment]
Yes, that worked. Guys, congrats again your work! I expect to be using your graphs a lot, so I would love to be a contributor to the project in the future.

**Comment by MarcelGerber** [comment]
Great you get some use out of the grapher, and very good that you could figure out by yourself how to import your data!

The handling of dates is indeed a little hacky at the moment since it was tacked on quickly when we needed it back in March, but we're currently working on making it more of a first-class feature and thus imports should be easier / more intuitive in a few weeks' time.

> Yes, that worked. Guys, congrats again your work! I expect to be using your graphs a lot, so I would love to be a contributor to the project in the future.

Great! Contributions are always welcome and we would be glad to accept your contributions.
If you'd like to work on a bigger issue, it's probably better to first open an issue so we can first discuss whether we need a particular feature or fix.
You can also contact me by mail (marcel@ourworldindata.org) if you need help in figuring something out.
