### ISSUE TITLE
Port the country name standardizer to JavaScript

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#63]
Aibek wrote this useful tool for standardizing country names between different formats, a common problem in working with economics datasets: https://github.com/owid/owid-grapher/tree/master/country_name_tool

This is currently server-side code, but we'd like to do most of it client-side. It should be possible to preload the necessary entity data and process the CSV entirely in the browser.

I think the only server-side step should be the remembering of choices in the case when manual resolution is needed.

Once ported to client-side JS, we could then think about moving the standardizer out of the admin and making it a standalone public tool.

**Comment by sherinkurian** [comment]
hi Jaiden, would it be possible to share data from `country_name_tool_countrydata` and `country_name_tool_countryname` - to test client-side performance. it's not a blocker though.

**Comment by OurWorldInData-User** [comment]
Dear Sherin,

Your version of the Country Tool is fantastic! 
https://owid.cloud/admin/standardize

I am sure many researchers will be very, very happy to be able to use this tool as it is one of the most tedious recurring tasks to do deal with these country name standardizations when you combine many datasets.

I tried it out with a dataset and it works very nicely!

One thing that will be needed – especially if we want to make it public – is a bit of explanation of how to use it.
Could there be a little text on the same page – maybe simply above the tool – where you explain the steps one has to take to standardize the country names?
– The file has to be a csv
– The country has to be saved in a row called "country"
– The output file will appear there to download
etc.

And more generally it is really, really cool that you are becoming part of the new team! Great to be working with you and if you have any questions, concerns, ideas just let me know.

Best,
Max

**Comment by HannahRitchie** [comment]
Hey Sherin,

Just tried out the new soon-to-be-public version of the Country Tool. It is really great! Super-fast and very straightforward to use. It it really cool that you are helping us out in this way - I think the people who use our stuff will be really grateful (and we are too, of course).

I have only a few small suggestions in addition to Max above:
- for it to be more intuitive/obvious for people to use I think next to the 'Potential candidates' title I would put 'Potential candidates (select below)'. This makes it obvious that they have to choose one for themselves.
- similarly in the next column I would change 'Custom Name' to 'Or enter a Custom Name'. This makes it obvious to people that they have to do one or the other (some may think they have to do both, or get confused there).

Thanks again for all of your help!
Hannah

**Comment by JoeHasell** [comment]
Hi Sherin,

Really well done – this is going to be an incredibly useful tool for a lot of people! As Hannah says, it runs impressively fast.

I'd emphasise what Max said about proving some instructions. In a similar vein, where someone fails to upload a csv in the right structure (e.g. with 'Country' as a title), it would perhaps be helpful if an error message could be produced. At the moment nothing happens, and a user might just think that the tool was broken or whatever and not realise their mistake.

Thanks again!
Joe

**Comment by DianaBeltekian** [comment]
Hi Sherin! 

Thank you for your work on the country tool! As the others have already mentioned, this will be incredibly useful when putting together new data sets. 

I've tested it out and it working really well! 

Some points I've noted down from doing some tinkering:
 
•	Going from a non-standard country name to OWID output format works well, as well as for getting the continent name and continent codes. I didn't run into any problems.
•	Output format:  ISO3166-1 ALPHA 2 CODE - Kosovo is unmatched, likely because as a partially recognised state it hasn’t been included. I looked it up and the European Commission, IMF, and other organisations usually use a temporary country code XK. 
•	ISO3166-1 ALPHA-3 CODE - works well, same country name issue for Kosovo here
•	The IMF country code appears correct for countries I double checked, but the original name appears in red (any reason for this format? May be a bug?). This is when going from non-standardised country names to IMF country codes.
•	Country names appear in red when converting from non-standardized country names to COW codes
•	UNCTAD 3 letter codes unavailable for Switzerland, Canada, Denmark, Spain, Finland, and other countries too.
•	When converting from non-standard country names to some output formats, e.g. Kansas events data system, the output names are not found. Would it be possible to convert from a non-standard country name to OWID standardized names and then to a final output code to avoid this problem?
•	At the moment when downloading the country standardized .csv you can only have one column specifying the standardized country names, codes etc. Would it be possible to have multiple columns of formatted output, i.e. choosing the OWID country name, IMF codes, and continent name for example. Or would that be quite complicated to introduce? 
•	Where the country name is the ISO3166-1 ALPHA-3 CODE, the tool has a hard time providing a standardized name in a different output format. No standardized names are specified, instead it offers a number of potential candidates for each row. E.g. "ABW" is for Aruba but all the suggestions appearing are Zimbabwe. For other countries, the potential suggestions are correct though.

Thanks again for all your work! Very much appreciated! 
Diana

**Comment by sherinkurian** [comment]
Hi all, 

This made my day :) So nice to hear that the tool is working as expected for the most part and thanks for all the feedback/suggestions.

Fix for the bug @DianaBeltekian reported with Alpha2/Alpha3 codes is ready and should be out soon. Need to dig into the rest.

I will add some validation/documentation as suggested to help with usability. It should be available by this weekend.

Regarding the feature request of supporting multiple output formats, it is definitely doable but will need some overhaul. Happy to tackle it next after the first version is ironed out.

Thank you!

**Comment by sherinkurian** [comment]
Hi Max, Hannah, Joe, Diana:

All of the critical improvements/fixes requested are here - https://github.com/owid/owid-grapher/pull/78. Let me know if the new update has missed anything that could block its rollout. I probably went a bit overboard with the instructions; so i would be fine with removing/editing any text as well :)

@DianaBeltekian - UNCTAD codes for Switzerland etc are missing in the database which is why it's not showing up. Note that the old tool did not complain about it but the resulting file would be missing the code for these countries. Unsure if that was for a reason but I like that the new tool is more explicit about it. You can still download the file even if there are any unmatched entries.
 
A long-term solution would be to allow saving "Custom Names" back in the database and to do this nicely, we will need to make some fundamental changes on the backend (in my opinion!). I will sync with Jaiden separately but it will probably be something that the team will need eventually.

Max - Showing the map makes sense! I am guessing what you are asking is something similar to the Preview of the world map that is shown on the Variables page. It is a logical next step to have in the tool. I will look into it.

Thanks again everyone for the detailed feedback.

**Comment by OurWorldInData-User** [comment]
Amazing! Thank you Sherin!

**Comment by DianaBeltekian** [comment]
Thank you Sherin! Appreciate it!

**Comment by DianaBeltekian** [comment]
Hi Sherin, 

I have one very minor suggestion having used the tool today. When I download the .csv file, the 'Our World in Data' name for the Bahamas appears in two columns. So rather than having 'The Bahamas' under the OWID standardized name column, it appears in two with 'The' in one, and 'Bahamas' in another, as below. 

![image](https://user-images.githubusercontent.com/41151556/42817316-a9363b24-89c5-11e8-97b3-cb8175313c30.png)


Not at all urgent, but I thought I should make a note here! 
Thanks! 
Diana

**Comment by sherinkurian** [comment]
Hi Diana, 
Thank you for the bug report! This is my bad - There is a fix in the pull request so hopefully you will see it soon.

**Comment by mispy** [comment]
The version that Sherin updated is available internally here: https://owid.cloud/admin/standardize

If people are happy with the core functionality now, I'll go ahead replace the old standardizer and update the instructions and such-- there are a couple of old case-sensitivity and unicode formatting bugs that are fixed in Sherin's implementation. Then we can work on turning it into a public page.
