### ISSUE TITLE
"Closest time" definition unexpected behavior.

### ISSUE THREAD

**Issue by paulochang** [owid/owid-grapher#762]
While playing around with the covid vaccination tracker, I noticed that for Spain was showing up always (even tho it appears to have just a single point on Jan. 4, 2021) , no matter the data range that I was selecting.  (see attached picture)

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/4237241/103559512-8a863e00-4eb6-11eb-85ed-50caea2f5309.png">

My theory is that the closest time function, because it takes the min or max time in unbounded sets... behaves unexpectedly for single data point sets. (as this is both the min and max time)

See:
https://github.com/owid/owid-grapher/blob/c56111d1b57d28ca340c9fa10fc61e72a2525fe1/grapher/utils/Util.ts#L583

IMHO, if I have a max range of say.. dec 31st. It shouldn't show up the datapoint after this date. Which seems to be the case if there's more than 1 data point in the set.

It seems to be more explicit in the table view, where hovering over this value will show the following note:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/4237241/103559714-de912280-4eb6-11eb-9503-bbbb1194b578.png">

**Comment by danielgavrilov** [comment]
Hi @paulochang, thanks for writing this up and digging into the code! 🙂 

The charts have a `tolerance` property: 

https://github.com/owid/owid-grapher/blob/8372b99176c0018e71fbe064435a8d46e48bb205/owidTable/LegacyVariableCode.ts#L24

https://github.com/owid/owid-grapher/blob/8372b99176c0018e71fbe064435a8d46e48bb205/grapher/mapCharts/MapConfig.ts#L19

This defines the maximum number of time steps (can be days or years) to go forwards or backwards to display the closest value if there is no value available for the selected time. For the vaccinations data, we currently have this set to a high value (30 days) because this data is currently very patchy.

<img width="462" alt="Screenshot 2021-01-04 at 19 15 16" src="https://user-images.githubusercontent.com/1308115/103570998-05a12180-4ec2-11eb-829e-cc8c39c385e7.png">

This might be unreasonably high as you point out – we will review and maybe change it!

Thanks for digging in! If you have any more feedback or questions, do let us know! Open an issue, or feel free to email me at daniel@ourworldindata.org.

**Comment by paulochang** [comment]
Thanks for the quick reply! I love your work guys!
